import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { FLAVOR_COL, HEALTH_COL, CUISINE_COL } from './preferenceColMap';
import { getFallbackImage } from '../lib/dishImageFallback';
import { getUserPrefs } from '../lib/userPrefs';
import { getUserId } from '../lib/userId';
import { applyCuisineFilter, type CuisineMode } from '../lib/cuisineFilter';

// ── Public types ──────────────────────────────────────────────────────────

// ── Tray-based prep step (for domestic helper 菲佣) ──────────────────────────
// Tray assignment: A=main protein | B=hard veg/root | C=soft veg/leafy
//                 D=aromatics (葱姜蒜) | E=pre-mixed sauce | F=garnish
export interface PrepStep {
  tray: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
  ingredient_zh: string;
  ingredient_en: string;
  amount_g: number;
  action_zh: string;  // precise: cut size, rinse, soak, etc.
  action_en: string;
}

// ── Precise cooking step (for cooking robot) ──────────────────────────────────
export interface CookStep {
  step: number;
  action_zh: string;  // includes heat level, duration, weight, visual cue
  action_en: string;
  duration_min: number;
}

export interface SupabaseDish {
  // ── Raw DB fields ────────────────────────────────────────────────────────
  id: string;
  title_zh: string;
  origin_cuisine: string;
  flavor_tags: string[];
  health_benefit_tags: string[];
  seasonal_tag: string;
  image_url: string;
  main_ingredient: string; // e.g. 'beef' | 'chicken' | 'fish' | 'veggie' | 'other'
  is_vegan: boolean;       // Buddhist-friendly / pure plant-based
  course_type?: string;
  cook_time_min?: number;
  description_zh?: string;

  // ── Steps (generated by gen-dish-steps, stored as JSONB in dishes table) ──
  // Available for ANY dish in menu (AI-generated or user-swapped) via select('*')
  prep_steps_json?: PrepStep[] | null;  // tray-based prep for helper
  cook_steps_json?: CookStep[] | null;  // precise steps for cooking robot

  // ── UI adapter fields (set by enrichDish, consumed by Home.tsx) ──────────
  title: string;        // i18n: title_zh | title_en
  desc: string;         // i18n: description_zh | description_en | derived
  img: string;          // alias for image_url (with fallback)
  type: string;         // VEGGIE | SEAFOOD | SOUP | MEAT
  highlight: boolean;
  is_vegetarian: boolean;
  description_en: string; // kept for backward-compat

  // ── Raw record preserved for debugging / future use ──────────────────────
  _raw: Record<string, unknown>;
}

export interface UserProfile5D {
  hometown_cuisine: string | null;
  dietary_goal: string | null;
  taste_pref: string | null;
  age_group: string | null;
  avoid_tags: string[];
}

export interface SolarTerm {
  name_zh: string;
  name_en: string;
  pinyin: string;
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  // Scoring modifiers
  healthBoostTags: string[];   // health_benefit_tags → goal score boost
  healthBonus: number;
  flavorBoostTags: string[];   // flavor_tags → taste score boost
  flavorBonus: number;
  flavorPenaltyTags: string[]; // flavor_tags → taste score penalty
  flavorPenalty: number;
  // Food philosophy summary for UI display
  philosophy_zh: string;
  philosophy_en: string;
}

// ── 24 Solar Terms ────────────────────────────────────────────────────────
//
// Each entry covers ~15 days starting from month/day.
// Scoring philosophy:
//   • Spring (春): 疏肝祛湿 — damp_clear, detox, light
//   • Summer (夏): 清热解暑 — detox, damp_clear, penalize spicy
//   • Autumn (秋): 润燥贴膘 — maintain early, muscle_gain late
//   • Winter (冬): 温补进补 — maintain, muscle_gain (especially 冬至)

const SOLAR_TERMS: SolarTerm[] = [
  // ── SPRING ───────────────────────────────────────────────────────────
  {
    name_zh: '立春', name_en: 'Start of Spring', pinyin: 'Lìchūn',
    season: 'spring', month: 2, day: 4,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '疏肝理气，清淡为主',
    philosophy_en: 'Soothe the liver, prefer light dishes',
  },
  {
    name_zh: '雨水', name_en: 'Rain Water', pinyin: 'Yǔshuǐ',
    season: 'spring', month: 2, day: 19,
    healthBoostTags: ['maintain', 'damp_clear'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾祛湿，温和进补',
    philosophy_en: 'Strengthen spleen, clear dampness',
  },
  {
    name_zh: '惊蛰', name_en: 'Awakening of Insects', pinyin: 'Jīngzhé',
    season: 'spring', month: 3, day: 6,
    healthBoostTags: ['detox', 'maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '以梨润肺，清火排毒',
    philosophy_en: 'Moisten lungs, clear internal heat',
  },
  {
    name_zh: '春分', name_en: 'Spring Equinox', pinyin: 'Chūnfēn',
    season: 'spring', month: 3, day: 21,
    healthBoostTags: ['maintain'], healthBonus: 0.10,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '阴阳平衡，饮食均衡',
    philosophy_en: 'Balance yin and yang through varied diet',
  },
  {
    name_zh: '清明', name_en: 'Clear and Bright', pinyin: 'Qīngmíng',
    season: 'spring', month: 4, day: 5,
    healthBoostTags: ['maintain', 'detox'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '清补柔肝，忌油腻',
    philosophy_en: 'Gentle nourishing, avoid greasy foods',
  },
  {
    name_zh: '谷雨', name_en: 'Grain Rain', pinyin: 'Gǔyǔ',
    season: 'spring', month: 4, day: 20,
    healthBoostTags: ['damp_clear'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '祛湿健脾为要，宜饮谷雨茶',
    philosophy_en: 'Prime season for damp-clearing foods',
  },

  // ── SUMMER ───────────────────────────────────────────────────────────
  {
    name_zh: '立夏', name_en: 'Start of Summer', pinyin: 'Lìxià',
    season: 'summer', month: 5, day: 6,
    healthBoostTags: ['damp_clear', 'maintain'], healthBonus: 0.20,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾养心，清淡祛湿',
    philosophy_en: 'Nourish the heart, light and damp-clearing',
  },
  {
    name_zh: '小满', name_en: 'Grain Buds', pinyin: 'Xiǎomǎn',
    season: 'summer', month: 5, day: 21,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '清热利湿，忌辛辣助热',
    philosophy_en: 'Clear heat and dampness, avoid spicy',
  },
  {
    name_zh: '芒种', name_en: 'Grain in Ear', pinyin: 'Mángzhòng',
    season: 'summer', month: 6, day: 6,
    healthBoostTags: ['detox'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '开胃健脾，清淡排毒',
    philosophy_en: 'Stimulate appetite, light detoxifying foods',
  },
  {
    name_zh: '夏至', name_en: 'Summer Solstice', pinyin: 'Xiàzhì',
    season: 'summer', month: 6, day: 21,
    healthBoostTags: ['damp_clear', 'detox'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '清热消暑，多食苦味祛火',
    philosophy_en: 'Beat summer heat, bitter foods to reduce fire',
  },
  {
    name_zh: '小暑', name_en: 'Minor Heat', pinyin: 'Xiǎoshǔ',
    season: 'summer', month: 7, day: 7,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '消暑利湿，绿豆薏米当道',
    philosophy_en: 'Cool and clear — mung beans and pearl barley season',
  },
  {
    name_zh: '大暑', name_en: 'Major Heat', pinyin: 'Dàshǔ',
    season: 'summer', month: 7, day: 23,
    // Strongest summer-clearing node — maximum bonuses
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.30,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.25,
    philosophy_zh: '一年最热，清热祛暑滋阴为要',
    philosophy_en: 'Peak heat: maximum damp-clearing and yin-nourishing',
  },

  // ── AUTUMN ───────────────────────────────────────────────────────────
  {
    name_zh: '立秋', name_en: 'Start of Autumn', pinyin: 'Lìqiū',
    season: 'autumn', month: 8, day: 7,
    // 贴秋膘 — traditional meat-gaining custom after summer
    healthBoostTags: ['muscle_gain', 'maintain'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '贴秋膘，补充夏季消耗',
    philosophy_en: 'Store autumn fat — replenish after summer',
  },
  {
    name_zh: '处暑', name_en: 'End of Heat', pinyin: 'Chǔshǔ',
    season: 'autumn', month: 8, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '润肺防燥，梨银耳为佳',
    philosophy_en: 'Moisten lungs against autumn dryness',
  },
  {
    name_zh: '白露', name_en: 'White Dew', pinyin: 'Báilù',
    season: 'autumn', month: 9, day: 8,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.10,
    philosophy_zh: '滋阴润燥，少食辛辣',
    philosophy_en: 'Nourish yin, reduce spicy to protect lungs',
  },
  {
    name_zh: '秋分', name_en: 'Autumnal Equinox', pinyin: 'Qiūfēn',
    season: 'autumn', month: 9, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '平补为主，阴阳调和',
    philosophy_en: 'Balanced nourishing, harmony of yin and yang',
  },
  {
    name_zh: '寒露', name_en: 'Cold Dew', pinyin: 'Hánlù',
    season: 'autumn', month: 10, day: 8,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补养胃，秋蟹正肥',
    philosophy_en: 'Warm nourishing — peak season for crab',
  },
  {
    name_zh: '霜降', name_en: "Frost's Descent", pinyin: 'Shuāngjiàng',
    season: 'autumn', month: 10, day: 23,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '羊肉栗子当道，温补正当时',
    philosophy_en: 'Lamb and chestnuts — prime warming season',
  },

  // ── WINTER ───────────────────────────────────────────────────────────
  {
    name_zh: '立冬', name_en: 'Start of Winter', pinyin: 'Lìdōng',
    season: 'winter', month: 11, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '补冬进补，饺子暖胃',
    philosophy_en: 'Begin winter nourishing — dumplings and warming broths',
  },
  {
    name_zh: '小雪', name_en: 'Minor Snow', pinyin: 'Xiǎoxuě',
    season: 'winter', month: 11, day: 22,
    healthBoostTags: ['maintain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补阳气，腊肉腌制正当时',
    philosophy_en: 'Warm yang energy, cured meats season begins',
  },
  {
    name_zh: '大雪', name_en: 'Major Snow', pinyin: 'Dàxuě',
    season: 'winter', month: 12, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '大补特补，羊肉炉火锅正季',
    philosophy_en: 'Deep nourishing — mutton hotpot season',
  },
  {
    name_zh: '冬至', name_en: 'Winter Solstice', pinyin: 'Dōngzhì',
    season: 'winter', month: 12, day: 22,
    // Most important winter node — maximum tonic boost
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.35,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '一年最重要的进补节气，北饺南汤圆',
    philosophy_en: 'Greatest tonic day — dumplings north, tang yuan south',
  },
  {
    name_zh: '小寒', name_en: 'Minor Cold', pinyin: 'Xiǎohán',
    season: 'winter', month: 1, day: 6,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温热为主，八宝粥驱寒',
    philosophy_en: 'Warming foods dominate — eight-treasure porridge',
  },
  {
    name_zh: '大寒', name_en: 'Major Cold', pinyin: 'Dàhán',
    season: 'winter', month: 1, day: 20,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '岁末大补，迎接新春',
    philosophy_en: 'Year-end deep nourishing before the new year',
  },
] as (SolarTerm & { month: number; day: number })[];

// ── Solar term calculator ─────────────────────────────────────────────────

// Find the solar term currently in effect (most recently started).
// Solar terms last ~15 days; we compare using a simple days-elapsed metric.
function getCurrentSolarTerm(): SolarTerm {
  const now   = new Date();
  const month = now.getMonth() + 1; // 1-12
  const day   = now.getDate();

  // Approximate "days elapsed since this term started" — handles year wrap-around
  function daysSinceStart(term: SolarTerm & { month: number; day: number }): number {
    let monthDiff = month - term.month;
    // If the term is ahead of current month in the calendar year, treat it as ~last year's instance
    if (monthDiff < 0) monthDiff += 12;
    return monthDiff * 30 + (day - term.day); // ~30 days/month is accurate enough
  }

  let current = SOLAR_TERMS[0] as SolarTerm;
  let minElapsed = Infinity;

  for (const term of SOLAR_TERMS as (SolarTerm & { month: number; day: number })[]) {
    const elapsed = daysSinceStart(term);
    if (elapsed >= 0 && elapsed < minElapsed) {
      minElapsed = elapsed;
      current = term;
    }
  }

  return current;
}

// ── Age profile system ────────────────────────────────────────────────────

interface AgeModifiers {
  wellnessTags: string[];
  wellnessBonus: number;
  tasteBoostTags: string[];
  tasteBonus: number;
  tastePenaltyTags: string[];
  tastePenalty: number;
}

const SENIOR_MODS: AgeModifiers = {   // 70后及之前
  wellnessTags:     ['maintain', 'pregnancy', 'damp_clear'],
  wellnessBonus:    0.50,
  tasteBoostTags:   ['light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy'],
  tastePenalty:     0.30,
};
const MIDDLE_MODS: AgeModifiers = {   // 80后
  wellnessTags:     ['maintain', 'lose_weight', 'damp_clear'],
  wellnessBonus:    0.20,
  tasteBoostTags:   [],
  tasteBonus:       0,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const YOUNG_MODS: AgeModifiers = {    // 90后
  wellnessTags:     ['muscle_gain'],
  wellnessBonus:    0.25,
  tasteBoostTags:   ['spicy', 'seafood'],
  tasteBonus:       0.15,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const CHILD_MODS: AgeModifiers = {    // 00后及之后
  wellnessTags:     ['maintain'],
  wellnessBonus:    0.15,
  tasteBoostTags:   ['sweet', 'light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy', 'sour'],
  tastePenalty:     0.35,
};

const AGE_GROUP_MAP: Array<{ keys: string[]; mods: AgeModifiers }> = [
  { keys: ['50后','60后','70后','pre1970','1950s','1960s','1970s','senior','elderly'], mods: SENIOR_MODS },
  { keys: ['80后','1980s','middle','adult'], mods: MIDDLE_MODS },
  { keys: ['90后','1990s','young','youth'],  mods: YOUNG_MODS  },
  { keys: ['00后','10后','2000s','2010s','child','teen','kid'],                       mods: CHILD_MODS  },
];

function resolveAgeModifiers(ageGroup: string | null): AgeModifiers {
  if (!ageGroup) return MIDDLE_MODS;
  const lower = ageGroup.toLowerCase();
  for (const { keys, mods } of AGE_GROUP_MAP) {
    if (keys.some(k => lower === k.toLowerCase() || lower.includes(k.toLowerCase()))) {
      return mods;
    }
  }
  return MIDDLE_MODS;
}

// ── Display helpers ───────────────────────────────────────────────────────

const CUISINE_LABELS: Record<string, string> = {
  sichuan:         'Sichuan Style',
  cantonese:       'Cantonese Style',
  jiangnan:        'Jiangnan Cuisine',
  northern:        'Northern Chinese',
  western:         'Western Style',
  japanese_korean: 'Japanese/Korean',
  southeast_asian: 'Southeast Asian',
};

// Extensible: add new tag → label mappings here without any DB schema change.
// The DB stores TEXT[], so any string value is valid.
const HEALTH_LABELS: Record<string, string> = {
  damp_clear:        'Damp-Clear',
  muscle_gain:       'High Protein',
  lose_weight:       'Low Calorie',
  maintain:          'Balanced',
  detox:             'Detox',
  pregnancy:         'Nourishing',
  authentic_hk:      'HK Classic',
  mood_boost:        '愉悦心情',
  anti_inflammation: '抗炎调理',
  immunity:          '增强免疫',
  beauty:            '美容养颜',
};

function deriveType(dish: any): string {
  const tags: string[] = dish.flavor_tags ?? [];
  if (tags.includes('veggie')) return 'VEGGIE';
  if (tags.includes('seafood')) return 'SEAFOOD';
  const seasonal = (dish.seasonal_tag ?? '').toLowerCase();
  if (seasonal.includes('soup') || seasonal.includes('stew')) return 'SOUP';
  return 'MEAT';
}

function deriveDescription(dish: any): string {
  const cuisine = CUISINE_LABELS[dish.origin_cuisine] ?? 'Signature Dish';
  const healthLabel = (dish.health_benefit_tags ?? [])
    .slice(0, 2)
    .map((t: string) => HEALTH_LABELS[t] ?? t.replace(/_/g, ' '))
    .join(', ');
  return healthLabel ? `${cuisine} · ${healthLabel}` : cuisine;
}

// ── Adapter: DB record → UI-friendly dish ────────────────────────────────
//
// Language is read from localStorage (set by LanguageContext) so this
// pure function stays outside React without needing the context hook.
// Fallback chain: explicit DB field → derived → empty string.

function enrichDish(dish: any, highlight: boolean): SupabaseDish {
  const lang = (localStorage.getItem('appLanguage') ?? 'zh') as 'en' | 'zh';
  const derivedDesc = deriveDescription(dish);

  const title =
    lang === 'zh'
      ? (dish.title_zh || dish.title_en || dish.title_zh || '')
      : (dish.title_en || dish.title_zh || '');

  const desc =
    lang === 'zh'
      ? (dish.description_zh || dish.description_en || derivedDesc)
      : (dish.description_en || dish.description_zh || derivedDesc);

  // Use stored URL if present, otherwise pick from curated fallback pool.
  // When AI-generated images are uploaded to storage and written to
  // dishes.image_url, this fallback is automatically bypassed.
  const img = (dish.image_url && dish.image_url.trim())
    ? dish.image_url
    : getFallbackImage(dish);

  return {
    ...dish,
    // UI adapter fields
    title,
    desc,
    img,
    // Computed classification
    is_vegetarian: (dish.flavor_tags ?? []).includes('veggie'),
    is_vegan: dish.is_vegan ?? false,
    type: deriveType(dish),
    highlight,
    // Keep for backward-compat
    description_en: dish.description_en || derivedDesc,
    // Steps — mapped from DB JSONB fields (available once gen-dish-steps runs)
    prep_steps_json: dish.prep_steps_json ?? null,
    cook_steps_json: dish.cook_steps_json ?? null,
    // Raw record for debugging
    _raw: dish,
  };
}

// ── Step 1: Hard filter ───────────────────────────────────────────────────

function hardFilter(
  pool: any[],
  avoidTags: string[],
  avoidIngredients: string[] = [],
  vegetarianOnly = false,
): any[] {
  return pool.filter(dish => {
    // Tag-based exclusion (flavor_tags + health_benefit_tags)
    if (avoidTags.length > 0) {
      const allTags = [...(dish.flavor_tags ?? []), ...(dish.health_benefit_tags ?? [])];
      if (allTags.some(tag => avoidTags.includes(tag))) return false;
    }
    // Ingredient-based exclusion (main_ingredient column)
    if (avoidIngredients.length > 0 && dish.main_ingredient) {
      if (avoidIngredients.includes(dish.main_ingredient)) return false;
    }
    // Vegetarian-only mode
    if (vegetarianOnly) {
      const isVeg = dish.is_vegan ||
        (dish.flavor_tags ?? []).includes('veggie') ||
        (dish.flavor_tags ?? []).includes('vegan');
      if (!isVeg) return false;
    }
    return true;
  });
}

// ── Step 2 + 3 + 6: Composite scoring ────────────────────────────────────
//
// Axis weights summary:
//   ① Hometown      30%   (5D profile)
//   ② Goal          40%   (5D profile + age modifier)
//   ③ Taste         30%   (5D profile + age modifier)
//   ④ Humidity      +0.30 bonus  (environment)
//   ⑤ Solar term    +0.12~+0.35  (culture / season)
//   ⑥ Feedback EMA  ±0.40 cap    (learned preferences — strongest recent signal)

function applyFeedbackScore(
  score: number,
  dish: any,
  prefScores: Record<string, number>,
): number {
  const flavorTags: string[] = dish.flavor_tags ?? [];
  const healthTags: string[] = dish.health_benefit_tags ?? [];
  const origin: string       = dish.origin_cuisine ?? '';

  let feedback = 0;

  // Accumulate pref scores for matching tags (each contributes proportionally)
  for (const tag of flavorTags) {
    const col = FLAVOR_COL[tag];
    if (col && prefScores[col]) feedback += prefScores[col] * 0.12;
  }
  for (const tag of healthTags) {
    const col = HEALTH_COL[tag];
    if (col && prefScores[col]) feedback += prefScores[col] * 0.12;
  }
  const cuisineCol = CUISINE_COL[origin];
  if (cuisineCol && prefScores[cuisineCol]) feedback += prefScores[cuisineCol] * 0.12;

  // Cap at ±0.40 so feedback never fully overrides the 5D profile
  return score + Math.max(-0.40, Math.min(0.40, feedback));
}

function scoreDish(
  dish: any,
  profile: UserProfile5D,
  humidity: number,
  solarTerm: SolarTerm,
  prefScores: Record<string, number>,
  spiceBoost = 0,
): number {
  const flavorTags: string[] = dish.flavor_tags ?? [];
  const healthTags: string[] = dish.health_benefit_tags ?? [];
  const origin:     string   = dish.origin_cuisine ?? '';
  const ageMods              = resolveAgeModifiers(profile.age_group);

  // ① Hometown (30%)
  const hometownScore =
    profile.hometown_cuisine && origin === profile.hometown_cuisine ? 1.0 : 0.0;

  // ② Goal (40%) + age wellness modifier
  let goalScore = 0.0;
  if (profile.dietary_goal && healthTags.includes(profile.dietary_goal)) goalScore = 1.0;
  if (healthTags.some(t => ageMods.wellnessTags.includes(t))) {
    goalScore = Math.min(1.0, goalScore + ageMods.wellnessBonus);
  }

  // ③ Taste (30%) + age taste modifier
  let tasteScore = 0.0;
  if (profile.taste_pref && flavorTags.includes(profile.taste_pref)) tasteScore = 1.0;
  if (flavorTags.some(t => ageMods.tasteBoostTags.includes(t))) {
    tasteScore = Math.min(1.0, tasteScore + ageMods.tasteBonus);
  }
  if (flavorTags.some(t => ageMods.tastePenaltyTags.includes(t))) {
    tasteScore = Math.max(0.0, tasteScore - ageMods.tastePenalty);
  }

  let score = hometownScore * 0.30 + goalScore * 0.40 + tasteScore * 0.30;

  // ④ Humidity correction (独立于节气)
  if (humidity > 85 && healthTags.includes('damp_clear')) {
    score += 0.30;
  }

  // ⑤ Solar term correction — seasonal food culture layer
  if (healthTags.some(t => solarTerm.healthBoostTags.includes(t))) {
    score += solarTerm.healthBonus;
  }
  if (flavorTags.some(t => solarTerm.flavorBoostTags.includes(t))) {
    score += solarTerm.flavorBonus;
  }
  if (flavorTags.some(t => solarTerm.flavorPenaltyTags.includes(t))) {
    score -= solarTerm.flavorPenalty;
  }

  // ⑥ User spice preference boost/penalty
  if (spiceBoost !== 0 && flavorTags.includes('spicy')) {
    score += spiceBoost;
  }

  // ⑦ Learned-preference signal — folds in user_preference_scores (positive
  // for tags the user has historically accepted, negative for rejected).
  // Values from the table are roughly in [-1, 1]; we sum matches across
  // flavor_tags + health_benefit_tags + origin_cuisine + seafood detector,
  // then dampen by LEARNED_WEIGHT so it nudges ranking without overriding
  // the explicit profile signal.
  const LEARNED_WEIGHT = 0.35;
  let learnedSum = 0;
  let learnedHits = 0;
  const SEAFOOD_INGS = new Set([
    'seafood','fish','shrimp','crab','shellfish','squid','scallop',
    'clam','lobster','salmon','tuna','cod','hairtail','seabass','oyster',
  ]);
  const add = (key: string) => {
    const v = prefScores[`pref_${key}`];
    if (typeof v === 'number' && v !== 0) {
      learnedSum += v;
      learnedHits += 1;
    }
  };
  flavorTags.forEach(t => add(t));
  healthTags.forEach(t => add(t));
  if (origin) add(origin);
  if (SEAFOOD_INGS.has((dish.main_ingredient ?? '').toLowerCase())) add('seafood');
  if (flavorTags.includes('veggie')) add('veggie');
  // Average across matching tags so a 10-tag dish doesn't dominate a 2-tag one
  if (learnedHits > 0) {
    score += (learnedSum / learnedHits) * LEARNED_WEIGHT;
  }

  return score;
}

// ── 70/30 meat-veggie balance ─────────────────────────────────────────────

function balanceMenu(scoredPool: any[], targetSize: number): any[] {
  const veggieTarget = Math.round(targetSize * 0.30);
  const meatTarget   = targetSize - veggieTarget;

  const veggies = scoredPool.filter(d => (d.flavor_tags ?? []).includes('veggie'));
  const meats   = scoredPool.filter(d => !(d.flavor_tags ?? []).includes('veggie'));

  let selectedMeats   = meats.slice(0, meatTarget);
  let selectedVeggies = veggies.slice(0, veggieTarget);

  if (selectedVeggies.length < veggieTarget) {
    selectedMeats = [...selectedMeats, ...meats.slice(meatTarget, meatTarget + (veggieTarget - selectedVeggies.length))];
  } else if (selectedMeats.length < meatTarget) {
    selectedVeggies = [...selectedVeggies, ...veggies.slice(veggieTarget, veggieTarget + (meatTarget - selectedMeats.length))];
  }

  return [...selectedMeats, ...selectedVeggies];
}

// ── Profile fetcher (Supabase → quickPrefs → legacy fallback) ────────────

async function fetchUserProfile(): Promise<UserProfile5D & { _prefs: ReturnType<typeof getUserPrefs> }> {
  // Always read the local prefs (quickPrefs is the primary anonymous source)
  const prefs = getUserPrefs();

  const userId = getUserId();
  if (userId) {
    try {
      const { data, error } = await supabase
        .from('user_profiles')
        .select('hometown_cuisine, dietary_goal, taste_pref, age_group, avoid_tags')
        .eq('id', userId)
        .single();
      if (!error && data) {
        // Merge DB profile with local quickPrefs (local takes precedence for avoid/spice)
        return {
          hometown_cuisine: data.hometown_cuisine ?? null,
          dietary_goal:     data.dietary_goal ?? prefs.dietaryGoal,
          taste_pref:       data.taste_pref ?? prefs.tastePref,
          age_group:        data.age_group ?? null,
          // Union of DB avoid_tags and locally derived avoid tags
          avoid_tags:       [...new Set([...(data.avoid_tags ?? []), ...prefs.avoidTags])],
          _prefs:           prefs,
        };
      }
    } catch { /* table not yet migrated — fall through */ }
  }

  // Anonymous path: use quickPrefs entirely
  return {
    hometown_cuisine: null,
    dietary_goal:     prefs.dietaryGoal,
    taste_pref:       prefs.tastePref,
    age_group:        null,
    avoid_tags:       prefs.avoidTags,
    _prefs:           prefs,
  };
}

// ── Swap options: same course_type FIRST, prefer same main_ingredient ────
//
// 原则：换菜后必须是"功能等价"的菜 — 汤换汤、主食换主食、蔬菜换蔬菜。
// 之前只过滤 main_ingredient 导致 "西班牙冷汤" (veggie/soup) 的替换池里
// 出现 "炒青菜" 这种非汤的 veggie 菜，搭配整体失衡。
//
// 现在两层：
//   1. 硬过滤：course_type 必须相同（如果有）
//   2. 软偏好：同 main_ingredient 排前面，不同的洗牌排后面

export async function fetchSwapOptions(
  currentDish: SupabaseDish,
  count = 3,
): Promise<SupabaseDish[]> {
  const ingredient = currentDish.main_ingredient;
  const courseType = currentDish.course_type;

  let query = supabase
    .from('dishes')
    .select('*')
    .neq('id', currentDish.id)
    .limit(count * 8); // fetch extra so we have room to prefer same-ingredient

  // ── Hard: same course_type ──
  // soup → soup, staple → staple, main_protein → main_protein,
  // veggie_dish → veggie_dish, dessert → dessert. If course_type missing,
  // fall back to ingredient filter so the swap is still meaningful.
  if (courseType) {
    query = query.eq('course_type', courseType);
  } else if (ingredient && ingredient !== 'other') {
    query = query.eq('main_ingredient', ingredient);
  }

  const { data, error } = await query;
  if (error || !data || data.length === 0) return [];

  // ── Soft: prefer same main_ingredient ──
  // E.g. swapping 红烧肉 (pork) prefers 糖醋里脊 (pork) over 葱油鸡 (chicken),
  // but both are valid main_protein swaps.
  const sameIng  = data.filter(d => d.main_ingredient === ingredient);
  const otherIng = data.filter(d => d.main_ingredient !== ingredient);
  const ordered = [
    ...sameIng.sort(() => Math.random() - 0.5),
    ...otherIng.sort(() => Math.random() - 0.5),
  ];
  return ordered.slice(0, count).map(d => enrichDish(d, false));
}

// ── Hook ─────────────────────────────────────────────────────────────────

/**
 * Calculate how many dishes to recommend based on meal type + headcount.
 *
 * 早餐: simpler, always 2-3 dishes regardless of people count
 * 午餐/晚餐: scales with effective headcount (kids count as 0.5)
 *   effective → dishes: 1-2→3, 3-4→4, 5-6→5, 7+→6
 */
export function calcDishCount(
  mealTime: '早餐' | '午餐' | '晚餐',
  adults: number,
  kids: number,
): number {
  if (mealTime === '早餐') return Math.min(3, Math.max(2, adults > 3 ? 3 : 2));
  const effective = adults + kids * 0.5;
  const count = Math.round(effective * 0.85) + 1;
  return Math.min(6, Math.max(3, count));
}

export function useRecommendDishes(
  mealTime: '早餐' | '午餐' | '晚餐' = '晚餐',
  veganOnly = false,
  adults = 2,
  kids = 0,
  cuisineMode: CuisineMode = 'chinese',
) {
  const [recommendedDishes, setRecommendedDishes] = useState<SupabaseDish[]>([]);
  const [currentSolarTerm, setCurrentSolarTerm]   = useState<SolarTerm | null>(null);
  const [prefScores, setPrefScores]               = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);

  const refresh = useCallback(() => setRefreshKey(k => k + 1), []);

  // Re-run when user updates preferences (from Settings or QuickSetup)
  useEffect(() => {
    const handler = () => setRefreshKey(k => k + 1);
    window.addEventListener('nutri-prefs-changed', handler);
    return () => window.removeEventListener('nutri-prefs-changed', handler);
  }, []);

  // Map UI label → DB meal_type values to include.
  // 午餐 intentionally includes 'dinner' — Chinese home lunch and dinner
  // share the same dish repertoire; most dinner dishes are equally suitable
  // for lunch. Without this, lunch returns 0 results (no lunch-tagged dishes).
  const mealTypeFilter: Record<string, string[]> = {
    '早餐': ['breakfast'],
    '午餐': ['lunch', 'dinner', 'all'],
    '晚餐': ['dinner', 'all'],
  };
  const allowedMealTypes = mealTypeFilter[mealTime] ?? ['dinner', 'all'];
  const dishCount = calcDishCount(mealTime, adults, kids);

  useEffect(() => {
    let cancelled = false;

    async function run() {
      try {
        setLoading(true);

        const humidity  = parseFloat(localStorage.getItem('current_humidity') ?? '75');
        const solarTerm = getCurrentSolarTerm();
        const profile   = await fetchUserProfile();

        // Load feedback-learned preference scores (best effort)
        let scores: Record<string, number> = {};
        const userId = getUserId();
        if (userId) {
          const { data: scoreRow } = await supabase
            .from('user_preference_scores')
            .select('*')
            .eq('user_id', userId)
            .single();
          if (scoreRow) scores = scoreRow as Record<string, number>;
        }

        // Filter by meal_type. `meal_type` may be NULL on older rows (treat as dinner/all).
        // We use 'in' + include NULL via OR filter.
        let dishQuery = supabase
          .from('dishes')
          .select('*')
          .or(`meal_type.in.(${allowedMealTypes.join(',')}),meal_type.is.null`)
          .limit(400);

        // 净食模式: only return is_vegan dishes
        if (veganOnly) {
          dishQuery = dishQuery.eq('is_vegan', true);
        }

        // Cuisine pre-filter — push the 中餐/西餐 toggle down to the DB so
        // top-N scoring picks from the right bucket instead of the UI
        // stripping survivors after the fact.
        dishQuery = applyCuisineFilter(dishQuery, cuisineMode);

        const { data: allDishes, error: fetchErr } = await dishQuery;
        if (fetchErr) throw fetchErr;

        const localPrefs = profile._prefs;
        const filtered = hardFilter(
          allDishes ?? [],
          profile.avoid_tags,
          localPrefs.avoidIngredients,
          localPrefs.vegetarianOnly,
        );

        const sorted = filtered
          .map(dish => ({
            dish,
            score: scoreDish(dish, profile, humidity, solarTerm, scores, localPrefs.spiceBoost),
          }))
          .sort((a, b) => b.score - a.score)
          .map(s => s.dish);

        const balanced = balanceMenu(sorted, dishCount);

        if (cancelled) return;

        setCurrentSolarTerm(solarTerm);
        setPrefScores(scores);
        setRecommendedDishes(balanced.map((d, i) => enrichDish(d, i === 0)));
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to fetch dishes');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    run();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshKey, mealTime, veganOnly, adults, kids, cuisineMode]);

  return { recommendedDishes, currentSolarTerm, prefScores, loading, error, refresh };
}
