// Smell 1 阶段 2 (v40): useRecommendDishes / scoreDish 链路已删除。本文件
// 只保留 SupabaseDish / SolarTerm / enrichDish / hardFilter / fetchSwapOptions /
// calcDishCount / isWholegrain / DINNER_HEAVY_TAGS 作可复用工具。
import { supabase } from '../lib/supabase';
import { getFallbackImage } from '../lib/dishImageFallback';
import { getUserPrefs } from '../lib/userPrefs';
import { type CuisineMode } from '../lib/cuisineFilter';
import { DISH_FIELDS } from '../lib/dishFields';

// ── Public types ──────────────────────────────────────────────────────────

// ── Tray-based prep step (for domestic helper 菲佣) ──────────────────────────
// Tray assignment: A=main protein | B=hard veg/root | C=soft veg/leafy
//                 D=aromatics (葱姜蒜) | E=pre-mixed sauce | F=garnish
export interface PrepStep {
  tray: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
  ingredient_zh: string;
  ingredient_en: string;
  amount_g: number;
  action_zh: string;  // precise: cut size, rinse, soak, etc.
  action_en: string;
  /** Suzie's Twist (from Simply Chinese Feasts framework) — quick
   *  supermarket-friendly substitutes when the user doesn't have the
   *  primary ingredient. Up to 3 ordered by closest analogue. */
  substitutes_zh?: string[];
  substitutes_en?: string[];
}

// ── Precise cooking step (for cooking robot) ──────────────────────────────────
export interface CookStep {
  step: number;
  action_zh: string;  // includes heat level, duration, weight, visual cue
  action_en: string;
  duration_min: number;
  /** 物性目标 / state target (from Simply Chinese Feasts framework) — the
   *  sensory checkpoint that tells a human cook this step is DONE. E.g.
   *  "肉变色 / 皮金黄酥脆 / 汤汁挂勺 / 静置定色". Critical for non-robot
   *  execution; cook_steps with duration alone are too mechanical for
   *  family helpers to gauge "done-ness". */
  state_target_zh?: string;
  state_target_en?: string;
}

export interface SupabaseDish {
  // ── Raw DB fields ────────────────────────────────────────────────────────
  id: string;
  title_zh: string;
  /** TICKET-029 — Backend 022 §C 给 924 dishes 灌入。可空 (老缓存行无此列时 fallback)。 */
  title_zh_hant?: string;
  title_en?: string;
  origin_cuisine: string;
  flavor_tags: string[];
  health_benefit_tags: string[];
  seasonal_tag: string;
  image_url: string;
  main_ingredient: string; // e.g. 'beef' | 'chicken' | 'fish' | 'veggie' | 'other'
  is_vegan: boolean;       // Buddhist-friendly / pure plant-based
  /** 适合儿童的菜——温和、熟悉格式、无辣无重油。Migration 017 自动 tag。
   *  scoreDish 在家有小孩 (nutri_kids>0) 时给 +0.20 加分。 */
  is_kid_friendly?: boolean;
  course_type?: string;
  cook_time_min?: number;
  description_zh?: string;

  // ── 文化背景 / cultural_note (from Simply Chinese Feasts framework) ────
  // One-paragraph backstory: origin, festival association, family meaning.
  // Surfaces in dish detail and (when present) lifts a dish into the
  // "节庆 / 文化菜" highlight rail on Home. Only populated for festive,
  // regional-iconic, or family-tradition dishes — most everyday dishes
  // leave this NULL to avoid clutter.
  cultural_note?: string | null;

  // ── Steps (generated by gen-dish-steps, stored as JSONB in dishes table) ──
  // Available for ANY dish in menu (AI-generated or user-swapped) via select('*')
  prep_steps_json?: PrepStep[] | null;  // tray-based prep for helper
  cook_steps_json?: CookStep[] | null;  // precise steps for cooking robot

  // ── 小美 / Thermomix-class robot compatibility ──────────────────────────
  // True when the dish can be made end-to-end by a cooking robot (no oven,
  // no deep fryer, no manual dim-sum folding). Backfilled by
  // scripts/backfill-xiaomei-compat.ts. Users with "我有小美" toggled on
  // see a 🤖 badge on these dishes and get a +0.15 score boost.
  xiaomei_compatible?: boolean;
  xiaomei_incompat_reason?: string | null;

  // ── P1 nutrition fields (营养主厨 / 中国居民膳食指南 2022) ─────────────
  // Filled by scripts/backfill-dish-nutrition.ts using Claude haiku.
  nutrition_kcal_per_serving?: number;
  oil_level?:    'low' | 'mid' | 'high';
  salt_level?:   'low' | 'mid' | 'high';
  sugar_level?:  'low' | 'mid' | 'high';
  protein_source?: Array<'fish' | 'meat' | 'poultry' | 'egg' | 'dairy' | 'soy' | 'shellfish' | 'tofu' | 'none'>;
  cook_method?:  'stir_fry' | 'steam' | 'boil' | 'stew' | 'pan_fry' | 'deep_fry' | 'grill' | 'roast' | 'bake' | 'mix_cold' | 'raw' | 'blanch' | 'braise';

  // ── UI adapter fields (set by enrichDish, consumed by Home.tsx) ──────────
  title: string;        // i18n: title_zh | title_en
  desc: string;         // i18n: description_zh | description_en | derived
  img: string;          // alias for image_url (with fallback)
  type: string;         // VEGGIE | SEAFOOD | SOUP | MEAT
  highlight: boolean;
  is_vegetarian: boolean;
  description_en: string; // kept for backward-compat

  // ── Raw record preserved for debugging / future use ──────────────────────
  _raw: Record<string, unknown>;
}

export interface UserProfile5D {
  hometown_cuisine: string | null;
  dietary_goal: string | null;
  taste_pref: string | null;
  age_group: string | null;
  avoid_tags: string[];
}

export interface SolarTerm {
  name_zh: string;
  name_en: string;
  pinyin: string;
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  // Scoring modifiers
  healthBoostTags: string[];   // health_benefit_tags → goal score boost
  healthBonus: number;
  flavorBoostTags: string[];   // flavor_tags → taste score boost
  flavorBonus: number;
  flavorPenaltyTags: string[]; // flavor_tags → taste score penalty
  flavorPenalty: number;
  // Food philosophy summary for UI display
  philosophy_zh: string;
  philosophy_en: string;
}

// ── 24 Solar Terms ────────────────────────────────────────────────────────
//
// Each entry covers ~15 days starting from month/day.
// Scoring philosophy:
//   • Spring (春): 疏肝祛湿 — damp_clear, detox, light
//   • Summer (夏): 清热解暑 — detox, damp_clear, penalize spicy
//   • Autumn (秋): 润燥贴膘 — maintain early, muscle_gain late
//   • Winter (冬): 温补进补 — maintain, muscle_gain (especially 冬至)

const SOLAR_TERMS: SolarTerm[] = [
  // ── SPRING ───────────────────────────────────────────────────────────
  {
    name_zh: '立春', name_en: 'Start of Spring', pinyin: 'Lìchūn',
    season: 'spring', month: 2, day: 4,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '疏肝理气，清淡为主',
    philosophy_en: 'Soothe the liver, prefer light dishes',
  },
  {
    name_zh: '雨水', name_en: 'Rain Water', pinyin: 'Yǔshuǐ',
    season: 'spring', month: 2, day: 19,
    healthBoostTags: ['maintain', 'damp_clear'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾祛湿，温和进补',
    philosophy_en: 'Strengthen spleen, clear dampness',
  },
  {
    name_zh: '惊蛰', name_en: 'Awakening of Insects', pinyin: 'Jīngzhé',
    season: 'spring', month: 3, day: 6,
    healthBoostTags: ['detox', 'maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '以梨润肺，清火排毒',
    philosophy_en: 'Moisten lungs, clear internal heat',
  },
  {
    name_zh: '春分', name_en: 'Spring Equinox', pinyin: 'Chūnfēn',
    season: 'spring', month: 3, day: 21,
    healthBoostTags: ['maintain'], healthBonus: 0.10,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '阴阳平衡，饮食均衡',
    philosophy_en: 'Balance yin and yang through varied diet',
  },
  {
    name_zh: '清明', name_en: 'Clear and Bright', pinyin: 'Qīngmíng',
    season: 'spring', month: 4, day: 5,
    healthBoostTags: ['maintain', 'detox'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '清补柔肝，忌油腻',
    philosophy_en: 'Gentle nourishing, avoid greasy foods',
  },
  {
    name_zh: '谷雨', name_en: 'Grain Rain', pinyin: 'Gǔyǔ',
    season: 'spring', month: 4, day: 20,
    healthBoostTags: ['damp_clear'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '祛湿健脾为要，宜饮谷雨茶',
    philosophy_en: 'Prime season for damp-clearing foods',
  },

  // ── SUMMER ───────────────────────────────────────────────────────────
  {
    name_zh: '立夏', name_en: 'Start of Summer', pinyin: 'Lìxià',
    season: 'summer', month: 5, day: 6,
    healthBoostTags: ['damp_clear', 'maintain'], healthBonus: 0.20,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾养心，清淡祛湿',
    philosophy_en: 'Nourish the heart, light and damp-clearing',
  },
  {
    name_zh: '小满', name_en: 'Grain Buds', pinyin: 'Xiǎomǎn',
    season: 'summer', month: 5, day: 21,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '清热利湿，忌辛辣助热',
    philosophy_en: 'Clear heat and dampness, avoid spicy',
  },
  {
    name_zh: '芒种', name_en: 'Grain in Ear', pinyin: 'Mángzhòng',
    season: 'summer', month: 6, day: 6,
    healthBoostTags: ['detox'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '开胃健脾，清淡排毒',
    philosophy_en: 'Stimulate appetite, light detoxifying foods',
  },
  {
    name_zh: '夏至', name_en: 'Summer Solstice', pinyin: 'Xiàzhì',
    season: 'summer', month: 6, day: 21,
    healthBoostTags: ['damp_clear', 'detox'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '清热消暑，多食苦味祛火',
    philosophy_en: 'Beat summer heat, bitter foods to reduce fire',
  },
  {
    name_zh: '小暑', name_en: 'Minor Heat', pinyin: 'Xiǎoshǔ',
    season: 'summer', month: 7, day: 7,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '消暑利湿，绿豆薏米当道',
    philosophy_en: 'Cool and clear — mung beans and pearl barley season',
  },
  {
    name_zh: '大暑', name_en: 'Major Heat', pinyin: 'Dàshǔ',
    season: 'summer', month: 7, day: 23,
    // Strongest summer-clearing node — maximum bonuses
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.30,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.25,
    philosophy_zh: '一年最热，清热祛暑滋阴为要',
    philosophy_en: 'Peak heat: maximum damp-clearing and yin-nourishing',
  },

  // ── AUTUMN ───────────────────────────────────────────────────────────
  {
    name_zh: '立秋', name_en: 'Start of Autumn', pinyin: 'Lìqiū',
    season: 'autumn', month: 8, day: 7,
    // 贴秋膘 — traditional meat-gaining custom after summer
    healthBoostTags: ['muscle_gain', 'maintain'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '贴秋膘，补充夏季消耗',
    philosophy_en: 'Store autumn fat — replenish after summer',
  },
  {
    name_zh: '处暑', name_en: 'End of Heat', pinyin: 'Chǔshǔ',
    season: 'autumn', month: 8, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '润肺防燥，梨银耳为佳',
    philosophy_en: 'Moisten lungs against autumn dryness',
  },
  {
    name_zh: '白露', name_en: 'White Dew', pinyin: 'Báilù',
    season: 'autumn', month: 9, day: 8,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.10,
    philosophy_zh: '滋阴润燥，少食辛辣',
    philosophy_en: 'Nourish yin, reduce spicy to protect lungs',
  },
  {
    name_zh: '秋分', name_en: 'Autumnal Equinox', pinyin: 'Qiūfēn',
    season: 'autumn', month: 9, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '平补为主，阴阳调和',
    philosophy_en: 'Balanced nourishing, harmony of yin and yang',
  },
  {
    name_zh: '寒露', name_en: 'Cold Dew', pinyin: 'Hánlù',
    season: 'autumn', month: 10, day: 8,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补养胃，秋蟹正肥',
    philosophy_en: 'Warm nourishing — peak season for crab',
  },
  {
    name_zh: '霜降', name_en: "Frost's Descent", pinyin: 'Shuāngjiàng',
    season: 'autumn', month: 10, day: 23,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '羊肉栗子当道，温补正当时',
    philosophy_en: 'Lamb and chestnuts — prime warming season',
  },

  // ── WINTER ───────────────────────────────────────────────────────────
  {
    name_zh: '立冬', name_en: 'Start of Winter', pinyin: 'Lìdōng',
    season: 'winter', month: 11, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '补冬进补，饺子暖胃',
    philosophy_en: 'Begin winter nourishing — dumplings and warming broths',
  },
  {
    name_zh: '小雪', name_en: 'Minor Snow', pinyin: 'Xiǎoxuě',
    season: 'winter', month: 11, day: 22,
    healthBoostTags: ['maintain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补阳气，腊肉腌制正当时',
    philosophy_en: 'Warm yang energy, cured meats season begins',
  },
  {
    name_zh: '大雪', name_en: 'Major Snow', pinyin: 'Dàxuě',
    season: 'winter', month: 12, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '大补特补，羊肉炉火锅正季',
    philosophy_en: 'Deep nourishing — mutton hotpot season',
  },
  {
    name_zh: '冬至', name_en: 'Winter Solstice', pinyin: 'Dōngzhì',
    season: 'winter', month: 12, day: 22,
    // Most important winter node — maximum tonic boost
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.35,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '一年最重要的进补节气，北饺南汤圆',
    philosophy_en: 'Greatest tonic day — dumplings north, tang yuan south',
  },
  {
    name_zh: '小寒', name_en: 'Minor Cold', pinyin: 'Xiǎohán',
    season: 'winter', month: 1, day: 6,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温热为主，八宝粥驱寒',
    philosophy_en: 'Warming foods dominate — eight-treasure porridge',
  },
  {
    name_zh: '大寒', name_en: 'Major Cold', pinyin: 'Dàhán',
    season: 'winter', month: 1, day: 20,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '岁末大补，迎接新春',
    philosophy_en: 'Year-end deep nourishing before the new year',
  },
] as (SolarTerm & { month: number; day: number })[];

// ── Solar term calculator ─────────────────────────────────────────────────

// Find the solar term currently in effect (most recently started).
// Solar terms last ~15 days; we compare using a simple days-elapsed metric.
export function getCurrentSolarTerm(): SolarTerm {
  const now   = new Date();
  const month = now.getMonth() + 1; // 1-12
  const day   = now.getDate();

  // Approximate "days elapsed since this term started" — handles year wrap-around
  function daysSinceStart(term: SolarTerm & { month: number; day: number }): number {
    let monthDiff = month - term.month;
    // If the term is ahead of current month in the calendar year, treat it as ~last year's instance
    if (monthDiff < 0) monthDiff += 12;
    return monthDiff * 30 + (day - term.day); // ~30 days/month is accurate enough
  }

  let current = SOLAR_TERMS[0] as SolarTerm;
  let minElapsed = Infinity;

  for (const term of SOLAR_TERMS as (SolarTerm & { month: number; day: number })[]) {
    const elapsed = daysSinceStart(term);
    if (elapsed >= 0 && elapsed < minElapsed) {
      minElapsed = elapsed;
      current = term;
    }
  }

  return current;
}

// ── Age profile system ────────────────────────────────────────────────────

interface AgeModifiers {
  wellnessTags: string[];
  wellnessBonus: number;
  tasteBoostTags: string[];
  tasteBonus: number;
  tastePenaltyTags: string[];
  tastePenalty: number;
}

const SENIOR_MODS: AgeModifiers = {   // 70后及之前
  wellnessTags:     ['maintain', 'pregnancy', 'damp_clear'],
  wellnessBonus:    0.50,
  tasteBoostTags:   ['light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy'],
  tastePenalty:     0.30,
};
const MIDDLE_MODS: AgeModifiers = {   // 80后
  wellnessTags:     ['maintain', 'lose_weight', 'damp_clear'],
  wellnessBonus:    0.20,
  tasteBoostTags:   [],
  tasteBonus:       0,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const YOUNG_MODS: AgeModifiers = {    // 90后
  wellnessTags:     ['muscle_gain'],
  wellnessBonus:    0.25,
  tasteBoostTags:   ['spicy', 'seafood'],
  tasteBonus:       0.15,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const CHILD_MODS: AgeModifiers = {    // 00后及之后
  wellnessTags:     ['maintain'],
  wellnessBonus:    0.15,
  tasteBoostTags:   ['sweet', 'light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy', 'sour'],
  tastePenalty:     0.35,
};

const AGE_GROUP_MAP: Array<{ keys: string[]; mods: AgeModifiers }> = [
  { keys: ['50后','60后','70后','pre1970','1950s','1960s','1970s','senior','elderly'], mods: SENIOR_MODS },
  { keys: ['80后','1980s','middle','adult'], mods: MIDDLE_MODS },
  { keys: ['90后','1990s','young','youth'],  mods: YOUNG_MODS  },
  { keys: ['00后','10后','2000s','2010s','child','teen','kid'],                       mods: CHILD_MODS  },
];

function resolveAgeModifiers(ageGroup: string | null): AgeModifiers {
  if (!ageGroup) return MIDDLE_MODS;
  const lower = ageGroup.toLowerCase();
  for (const { keys, mods } of AGE_GROUP_MAP) {
    if (keys.some(k => lower === k.toLowerCase() || lower.includes(k.toLowerCase()))) {
      return mods;
    }
  }
  return MIDDLE_MODS;
}

// ── Display helpers ───────────────────────────────────────────────────────

const CUISINE_LABELS: Record<string, string> = {
  sichuan:         'Sichuan Style',
  cantonese:       'Cantonese Style',
  jiangnan:        'Jiangnan Cuisine',
  northern:        'Northern Chinese',
  western:         'Western Style',
  japanese_korean: 'Japanese/Korean',
  southeast_asian: 'Southeast Asian',
};

// Extensible: add new tag → label mappings here without any DB schema change.
// The DB stores TEXT[], so any string value is valid.
const HEALTH_LABELS: Record<string, string> = {
  damp_clear:        'Damp-Clear',
  muscle_gain:       'High Protein',
  lose_weight:       'Low Calorie',
  maintain:          'Balanced',
  detox:             'Detox',
  pregnancy:         'Nourishing',
  authentic_hk:      'HK Classic',
  mood_boost:        '愉悦心情',
  anti_inflammation: '抗炎调理',
  immunity:          '增强免疫',
  beauty:            '美容养颜',
};

function deriveType(dish: any): string {
  const tags: string[] = dish.flavor_tags ?? [];
  if (tags.includes('veggie')) return 'VEGGIE';
  if (tags.includes('seafood')) return 'SEAFOOD';
  const seasonal = (dish.seasonal_tag ?? '').toLowerCase();
  if (seasonal.includes('soup') || seasonal.includes('stew')) return 'SOUP';
  return 'MEAT';
}

function deriveDescription(dish: any): string {
  const cuisine = CUISINE_LABELS[dish.origin_cuisine] ?? 'Signature Dish';
  const healthLabel = (dish.health_benefit_tags ?? [])
    .slice(0, 2)
    .map((t: string) => HEALTH_LABELS[t] ?? t.replace(/_/g, ' '))
    .join(', ');
  return healthLabel ? `${cuisine} · ${healthLabel}` : cuisine;
}

// ── Adapter: DB record → UI-friendly dish ────────────────────────────────
//
// Language is read from localStorage (set by LanguageContext) so this
// pure function stays outside React without needing the context hook.
// Fallback chain: explicit DB field → derived → empty string.

function enrichDish(dish: any, highlight: boolean): SupabaseDish {
  // TICKET-029 — expanded lang detection: 'zh' / 'zh-Hant' / 'en' / 'tl' / 'id'.
  // 'zh-Hant' picks new title_zh_hant column (Backend 022 §C ship).
  const lang = (localStorage.getItem('appLanguage') ?? 'zh') as 'en' | 'zh' | 'zh-Hant' | 'tl' | 'id';
  const derivedDesc = deriveDescription(dish);

  const title = (() => {
    if (lang === 'zh-Hant') return dish.title_zh_hant || dish.title_zh || dish.title_en || '';
    if (lang === 'zh')      return dish.title_zh || dish.title_zh_hant || dish.title_en || '';
    return dish.title_en || dish.title_zh || dish.title_zh_hant || '';   // en / tl / id
  })();

  const desc =
    lang === 'zh'
      ? (dish.description_zh || dish.description_en || derivedDesc)
      : (dish.description_en || dish.description_zh || derivedDesc);

  // Use stored URL if present, otherwise pick from curated fallback pool.
  // When AI-generated images are uploaded to storage and written to
  // dishes.image_url, this fallback is automatically bypassed.
  const img = (dish.image_url && dish.image_url.trim())
    ? dish.image_url
    : getFallbackImage(dish);

  return {
    ...dish,
    // UI adapter fields
    title,
    desc,
    img,
    // Computed classification
    is_vegetarian: (dish.flavor_tags ?? []).includes('veggie'),
    is_vegan: dish.is_vegan ?? false,
    type: deriveType(dish),
    highlight,
    // Keep for backward-compat
    description_en: dish.description_en || derivedDesc,
    // Steps — mapped from DB JSONB fields (available once gen-dish-steps runs)
    prep_steps_json: dish.prep_steps_json ?? null,
    cook_steps_json: dish.cook_steps_json ?? null,
    // 儿童友好 tag (migration 017) — drives +0.20 score boost when family has kids
    is_kid_friendly: dish.is_kid_friendly ?? false,
    // 文化背景 — null for everyday dishes, only festive/regional-iconic ones carry it
    cultural_note:   dish.cultural_note ?? null,
    // 小美 robot flags
    xiaomei_compatible:       dish.xiaomei_compatible ?? false,
    xiaomei_incompat_reason:  dish.xiaomei_incompat_reason ?? null,
    // P1 nutrition
    nutrition_kcal_per_serving: dish.nutrition_kcal_per_serving ?? undefined,
    oil_level:    dish.oil_level    ?? undefined,
    salt_level:   dish.salt_level   ?? undefined,
    sugar_level:  dish.sugar_level  ?? undefined,
    protein_source: dish.protein_source ?? undefined,
    cook_method:  dish.cook_method  ?? undefined,
    // Raw record for debugging
    _raw: dish,
  };
}

// ── Step 1: Hard filter ───────────────────────────────────────────────────

// Tag → set of main_ingredient values that should also trigger exclusion.
// Without this, a seafood-allergic user could see 鱼腐浸时蔬 because the dish
// is tagged main_ingredient='fish' but flavor_tags doesn't include 'seafood'.
// Allergen safety can't be probabilistic — we explicitly map each allergy
// keyword to all the underlying main_ingredient values that contain it.

// Weighted random sampling — mirrors the shape used in useWeeklyMenu.ts:245
// (kept inline here rather than exported because cross-importing the hooks
// risks a cycle through SupabaseDish). Higher-scored items have higher
// probability of being picked but lower-scored items can still win — this
// is what stops Home from showing the literal same top-N on every refresh.
function weightedRandom<T extends { score: number }>(
  candidates: T[],
  count: number,
): T[] {
  const result: T[] = [];
  const pool = [...candidates];
  for (let i = 0; i < count && pool.length > 0; i++) {
    const min = Math.min(...pool.map(c => c.score));
    const shifted = pool.map(c => ({ ...c, w: Math.max(0, c.score - min + 0.1) }));
    const total = shifted.reduce((s, c) => s + c.w, 0);
    let r = Math.random() * total;
    let idx = 0;
    for (let j = 0; j < shifted.length; j++) {
      r -= shifted[j].w;
      if (r <= 0) { idx = j; break; }
    }
    result.push(pool[idx]);
    pool.splice(idx, 1);
  }
  return result;
}

// hardFilter 用 dish.main_ingredient (英文 token, 30 distinct in DB) 做 equality
// 匹配 (`ingSet.has(ing)`). 关键词覆盖 DB 现有 token; gluten / tree_nuts 在
// 当前 schema 内无对应 main_ingredient 枚举 — 占位等 Database 070 补 schema 后
// 真生效 (e.g. 加 'wheat'/'noodle'/'flour' 或 'almond'/'walnut' token).
const ALLERGEN_TO_INGREDIENTS: Record<string, Set<string>> = {
  seafood: new Set([
    'seafood','fish','shrimp','crab','shellfish','squid','scallop',
    'clam','lobster','salmon','tuna','cod','hairtail','seabass','oyster',
  ]),
  // 鱼类细分 (避免 'seafood' 把所有海鲜一锅端时 fish-only 用户找不到出口)
  fish:    new Set(['fish','salmon','tuna','cod','hairtail','seabass']),
  dairy:   new Set(['dairy','milk','cheese','butter','cream','yogurt']),
  // 新 UI 006 用复数 'eggs'; 旧 'egg' key 保留向后兼容
  eggs:    new Set(['egg','duck_egg']),
  egg:     new Set(['egg','duck_egg']),
  // 占位 — DB 无对应 main_ingredient token, 待 Database 070 补 schema
  gluten:  new Set(['wheat','flour','noodle','bread','dumpling','bun']),
  soy:     new Set(['tofu','soy','soybean','soy_milk','tofu_skin']),
  // 占位 — DB 无对应 main_ingredient token, 待 Database 070 补 schema
  tree_nuts: new Set(['almond','walnut','cashew','hazelnut','pistachio','pine_nut','pecan','macadamia']),
  peanut:  new Set(['peanut']),
  beef:    new Set(['beef']),
};

function hardFilter(
  pool: any[],
  avoidTags: string[],
  avoidIngredients: string[] = [],
  vegetarianOnly = false,
): any[] {
  return pool.filter(dish => {
    // Tag-based exclusion (flavor_tags + health_benefit_tags)
    if (avoidTags.length > 0) {
      const allTags = [...(dish.flavor_tags ?? []), ...(dish.health_benefit_tags ?? [])];
      if (allTags.some(tag => avoidTags.includes(tag))) return false;
      // Allergen-safety extension: when avoidTags includes a known allergen
      // keyword (seafood/dairy/peanut/...), ALSO block any dish whose
      // main_ingredient falls under it. flavor_tags alone leaks 鱼腐浸时蔬,
      // 蜂蜜照烧三文鱼 etc. that aren't tagged 'seafood' explicitly.
      const ing = (dish.main_ingredient ?? '').toLowerCase();
      for (const allergen of avoidTags) {
        // UI 006 Q10 "其他自填" 写成 'other:芒果' — 留 v1.5 解析, hardFilter 跳过
        if (allergen.startsWith('other:')) continue;
        const ingSet = ALLERGEN_TO_INGREDIENTS[allergen];
        if (ingSet && ingSet.has(ing)) return false;
      }
    }
    // Ingredient-based exclusion (main_ingredient column)
    if (avoidIngredients.length > 0 && dish.main_ingredient) {
      if (avoidIngredients.includes(dish.main_ingredient)) return false;
    }
    // Vegetarian-only mode
    if (vegetarianOnly) {
      const isVeg = dish.is_vegan ||
        (dish.flavor_tags ?? []).includes('veggie') ||
        (dish.flavor_tags ?? []).includes('vegan');
      if (!isVeg) return false;
    }
    return true;
  });
}

// Smell 1 阶段 2 (v40): scoreDish / applyFeedbackScore / usagePowerUSM /
// useRecommendDishes 链路已彻底删除。所有评分逻辑迁移到
// src/hooks/useWeeklyMenu.ts scoreForWeek 内（9-axis）。本文件只保留
// SupabaseDish / SolarTerm / enrichDish / hardFilter / fetchSwapOptions /
// calcDishCount / isWholegrain / DINNER_HEAVY_TAGS 等可复用工具。

// Light-bias regex: dishes whose flavor profile reads as 重口 — these get
// a per-tag −0.10 dinner penalty so a 中国营养主厨 wouldn't put them on
// the family dinner table. Lunch / breakfast are untouched.
export const DINNER_HEAVY_TAGS = new Set(['salty', 'very_salty', 'oily', 'fried', 'rich']);

// 杂粮 lunch boost — Chinese dietary guideline says 午餐主食可加入杂粮
// 以补充 B 族维生素. Matches title keywords AND main_ingredient='grain'/'staple'
// so a 杂粮饭 ranks above plain white rice.
const WHOLEGRAIN_KEYWORDS = ['杂粮', '燕麦', '糙米', '玉米', '紫米', '黑米', '小米', '八宝', '藜麦', 'oat', 'quinoa', 'brown rice', 'multigrain', 'whole grain'];

export function isWholegrain(d: any): boolean {
  const title = (d.title_zh ?? d.title ?? '').toLowerCase();
  return WHOLEGRAIN_KEYWORDS.some(k => title.includes(k.toLowerCase()));
}


// ── Swap options: same course_type FIRST, prefer same main_ingredient ────
//
// 原则：换菜后必须是"功能等价"的菜 — 汤换汤、主食换主食、蔬菜换蔬菜。
// 之前只过滤 main_ingredient 导致 "西班牙冷汤" (veggie/soup) 的替换池里
// 出现 "炒青菜" 这种非汤的 veggie 菜，搭配整体失衡。
//
// 现在两层：
//   1. 硬过滤：course_type 必须相同（如果有）
//   2. 软偏好：同 main_ingredient 排前面，不同的洗牌排后面

export async function fetchSwapOptions(
  currentDish: SupabaseDish,
  count = 3,
): Promise<SupabaseDish[]> {
  const ingredient = currentDish.main_ingredient;
  const courseType = currentDish.course_type;

  // Pull current user prefs so the swap drawer respects the SAME
  // allergen/spice gates the main recommend hook applies. Without this
  // step the drawer would happily offer 麻辣豆腐 to a 不吃辣 user, or
  // 芝士焗虾 to a dairy-allergic user — exactly the trust break the
  // recommendation pipeline was designed to prevent.
  const localPrefs = getUserPrefs();

  let query = supabase
    .from('dishes')
    .select(DISH_FIELDS)
    .neq('id', currentDish.id)
    .limit(count * 12); // fetch extra so hardFilter has room to survive

  // ── Hard: same course_type ──
  // soup → soup, staple → staple, main_protein → main_protein,
  // veggie_dish → veggie_dish, dessert → dessert. If course_type missing,
  // fall back to ingredient filter so the swap is still meaningful.
  if (courseType) {
    query = query.eq('course_type', courseType);
  } else if (ingredient && ingredient !== 'other') {
    query = query.eq('main_ingredient', ingredient);
  }

  const { data, error } = await query;
  if (error || !data || data.length === 0) return [];

  // ── Apply same hard filters the recommend hook uses ──
  // avoidTags        → flavor_tags / health_benefit_tags exclude (spicy, dairy, …)
  // avoidIngredients → main_ingredient exclude (peanut, beef, …)
  const filtered = hardFilter(
    data,
    localPrefs.avoidTags,
    localPrefs.avoidIngredients,
    false,  // swap drawer shouldn't force vegan even if veganOnly is set elsewhere
  );
  const pool = filtered.length > 0 ? filtered : data;  // fall back to unfiltered if pool emptied

  // ── Soft: prefer same main_ingredient ──
  // E.g. swapping 红烧肉 (pork) prefers 糖醋里脊 (pork) over 葱油鸡 (chicken),
  // but both are valid main_protein swaps.
  const sameIng  = pool.filter(d => d.main_ingredient === ingredient);
  const otherIng = pool.filter(d => d.main_ingredient !== ingredient);
  const ordered = [
    ...sameIng.sort(() => Math.random() - 0.5),
    ...otherIng.sort(() => Math.random() - 0.5),
  ];
  return ordered.slice(0, count).map(d => enrichDish(d, false));
}

// ── Hook ─────────────────────────────────────────────────────────────────

/**
 * Calculate how many dishes to recommend based on meal type + headcount + cuisine.
 *
 * Cuisine-aware rules (user-confirmed 2026-05-17):
 *
 *   中餐 (chinese / all):
 *     早餐: 3-piece dry+wet+side template (1 人 = 2)
 *     午餐: n 道菜（"4 人 4 菜 / 三菜一汤"），min 2 / max 8
 *     晚餐: n + 1 道菜（晚餐比午餐多 1）
 *
 *   西餐 (western) — Western meals are structurally simpler:
 *     早餐: 3-piece (toast + drink + egg/fruit), same as 中餐
 *     午餐: 固定 2 道（1 主食 + 1 汤）— 西餐午餐通常是一份意面/三明治 + 一份汤
 *     晚餐: n 道菜（按人数）— matches 中餐午餐 count, still simpler than 中餐晚餐
 *
 * Kids count as 0.5 effective person.
 *
 * 中餐 vs 西餐 contrast for 4 people:
 *   中餐: 早 3 / 午 4 / 晚 5         西餐: 早 3 / 午 2 / 晚 4
 *
 * Previous version was cuisine-blind and over-counted 西餐午餐 — a 4-人
 * 西餐午餐 returned 5 dishes when the family actually eats a single
 * pasta + soup combo. Cuisine-aware split matches real table-setting habit.
 */
export function calcDishCount(
  mealTime: '早餐' | '午餐' | '晚餐',
  adults: number,
  kids: number,
  cuisineMode: CuisineMode = 'chinese',
): number {
  const eff = adults + kids * 0.5;
  if (mealTime === '早餐') return eff <= 1 ? 2 : 3;

  // 西餐: lunch is fixed 2 (staple + soup); dinner scales with headcount.
  if (cuisineMode === 'western') {
    if (mealTime === '午餐') return 2;
    return Math.max(2, Math.min(8, Math.round(eff)));   // 晚餐
  }

  // 中餐 / all — full 中国家庭饭桌
  const lunch = Math.max(2, Math.min(8, Math.round(eff)));
  return mealTime === '晚餐' ? Math.min(9, lunch + 1) : lunch;
}

