import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { FLAVOR_COL, HEALTH_COL, CUISINE_COL } from './preferenceColMap';
import { getFallbackImage } from '../lib/dishImageFallback';
import { getUserPrefs } from '../lib/userPrefs';
import { getUserId } from '../lib/userId';
import { applyCuisineFilter, type CuisineMode } from '../lib/cuisineFilter';
import { DISH_FIELDS } from '../lib/dishFields';
import { pickBreakfastCombo } from '../lib/breakfastCombos';
import { hometownMatches, hometownToDbBucket } from '../lib/hometownBuckets';
import { isNewUserSession } from '../lib/userLifecycle';

// ── Public types ──────────────────────────────────────────────────────────

// ── Tray-based prep step (for domestic helper 菲佣) ──────────────────────────
// Tray assignment: A=main protein | B=hard veg/root | C=soft veg/leafy
//                 D=aromatics (葱姜蒜) | E=pre-mixed sauce | F=garnish
export interface PrepStep {
  tray: 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
  ingredient_zh: string;
  ingredient_en: string;
  amount_g: number;
  action_zh: string;  // precise: cut size, rinse, soak, etc.
  action_en: string;
  /** Suzie's Twist (from Simply Chinese Feasts framework) — quick
   *  supermarket-friendly substitutes when the user doesn't have the
   *  primary ingredient. Up to 3 ordered by closest analogue. */
  substitutes_zh?: string[];
  substitutes_en?: string[];
}

// ── Precise cooking step (for cooking robot) ──────────────────────────────────
export interface CookStep {
  step: number;
  action_zh: string;  // includes heat level, duration, weight, visual cue
  action_en: string;
  duration_min: number;
  /** 物性目标 / state target (from Simply Chinese Feasts framework) — the
   *  sensory checkpoint that tells a human cook this step is DONE. E.g.
   *  "肉变色 / 皮金黄酥脆 / 汤汁挂勺 / 静置定色". Critical for non-robot
   *  execution; cook_steps with duration alone are too mechanical for
   *  family helpers to gauge "done-ness". */
  state_target_zh?: string;
  state_target_en?: string;
}

export interface SupabaseDish {
  // ── Raw DB fields ────────────────────────────────────────────────────────
  id: string;
  title_zh: string;
  origin_cuisine: string;
  flavor_tags: string[];
  health_benefit_tags: string[];
  seasonal_tag: string;
  image_url: string;
  main_ingredient: string; // e.g. 'beef' | 'chicken' | 'fish' | 'veggie' | 'other'
  is_vegan: boolean;       // Buddhist-friendly / pure plant-based
  /** 适合儿童的菜——温和、熟悉格式、无辣无重油。Migration 017 自动 tag。
   *  scoreDish 在家有小孩 (nutri_kids>0) 时给 +0.20 加分。 */
  is_kid_friendly?: boolean;
  course_type?: string;
  cook_time_min?: number;
  description_zh?: string;

  // ── 文化背景 / cultural_note (from Simply Chinese Feasts framework) ────
  // One-paragraph backstory: origin, festival association, family meaning.
  // Surfaces in dish detail and (when present) lifts a dish into the
  // "节庆 / 文化菜" highlight rail on Home. Only populated for festive,
  // regional-iconic, or family-tradition dishes — most everyday dishes
  // leave this NULL to avoid clutter.
  cultural_note?: string | null;

  // ── Steps (generated by gen-dish-steps, stored as JSONB in dishes table) ──
  // Available for ANY dish in menu (AI-generated or user-swapped) via select('*')
  prep_steps_json?: PrepStep[] | null;  // tray-based prep for helper
  cook_steps_json?: CookStep[] | null;  // precise steps for cooking robot

  // ── 小美 / Thermomix-class robot compatibility ──────────────────────────
  // True when the dish can be made end-to-end by a cooking robot (no oven,
  // no deep fryer, no manual dim-sum folding). Backfilled by
  // scripts/backfill-xiaomei-compat.ts. Users with "我有小美" toggled on
  // see a 🤖 badge on these dishes and get a +0.15 score boost.
  xiaomei_compatible?: boolean;
  xiaomei_incompat_reason?: string | null;

  // ── P1 nutrition fields (营养主厨 / 中国居民膳食指南 2022) ─────────────
  // Filled by scripts/backfill-dish-nutrition.ts using Claude haiku.
  nutrition_kcal_per_serving?: number;
  oil_level?:    'low' | 'mid' | 'high';
  salt_level?:   'low' | 'mid' | 'high';
  sugar_level?:  'low' | 'mid' | 'high';
  protein_source?: Array<'fish' | 'meat' | 'poultry' | 'egg' | 'dairy' | 'soy' | 'shellfish' | 'tofu' | 'none'>;
  cook_method?:  'stir_fry' | 'steam' | 'boil' | 'stew' | 'pan_fry' | 'deep_fry' | 'grill' | 'roast' | 'bake' | 'mix_cold' | 'raw' | 'blanch' | 'braise';

  // ── UI adapter fields (set by enrichDish, consumed by Home.tsx) ──────────
  title: string;        // i18n: title_zh | title_en
  desc: string;         // i18n: description_zh | description_en | derived
  img: string;          // alias for image_url (with fallback)
  type: string;         // VEGGIE | SEAFOOD | SOUP | MEAT
  highlight: boolean;
  is_vegetarian: boolean;
  description_en: string; // kept for backward-compat

  // ── Raw record preserved for debugging / future use ──────────────────────
  _raw: Record<string, unknown>;
}

export interface UserProfile5D {
  hometown_cuisine: string | null;
  dietary_goal: string | null;
  taste_pref: string | null;
  age_group: string | null;
  avoid_tags: string[];
}

export interface SolarTerm {
  name_zh: string;
  name_en: string;
  pinyin: string;
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  // Scoring modifiers
  healthBoostTags: string[];   // health_benefit_tags → goal score boost
  healthBonus: number;
  flavorBoostTags: string[];   // flavor_tags → taste score boost
  flavorBonus: number;
  flavorPenaltyTags: string[]; // flavor_tags → taste score penalty
  flavorPenalty: number;
  // Food philosophy summary for UI display
  philosophy_zh: string;
  philosophy_en: string;
}

// ── 24 Solar Terms ────────────────────────────────────────────────────────
//
// Each entry covers ~15 days starting from month/day.
// Scoring philosophy:
//   • Spring (春): 疏肝祛湿 — damp_clear, detox, light
//   • Summer (夏): 清热解暑 — detox, damp_clear, penalize spicy
//   • Autumn (秋): 润燥贴膘 — maintain early, muscle_gain late
//   • Winter (冬): 温补进补 — maintain, muscle_gain (especially 冬至)

const SOLAR_TERMS: SolarTerm[] = [
  // ── SPRING ───────────────────────────────────────────────────────────
  {
    name_zh: '立春', name_en: 'Start of Spring', pinyin: 'Lìchūn',
    season: 'spring', month: 2, day: 4,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '疏肝理气，清淡为主',
    philosophy_en: 'Soothe the liver, prefer light dishes',
  },
  {
    name_zh: '雨水', name_en: 'Rain Water', pinyin: 'Yǔshuǐ',
    season: 'spring', month: 2, day: 19,
    healthBoostTags: ['maintain', 'damp_clear'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾祛湿，温和进补',
    philosophy_en: 'Strengthen spleen, clear dampness',
  },
  {
    name_zh: '惊蛰', name_en: 'Awakening of Insects', pinyin: 'Jīngzhé',
    season: 'spring', month: 3, day: 6,
    healthBoostTags: ['detox', 'maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '以梨润肺，清火排毒',
    philosophy_en: 'Moisten lungs, clear internal heat',
  },
  {
    name_zh: '春分', name_en: 'Spring Equinox', pinyin: 'Chūnfēn',
    season: 'spring', month: 3, day: 21,
    healthBoostTags: ['maintain'], healthBonus: 0.10,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '阴阳平衡，饮食均衡',
    philosophy_en: 'Balance yin and yang through varied diet',
  },
  {
    name_zh: '清明', name_en: 'Clear and Bright', pinyin: 'Qīngmíng',
    season: 'spring', month: 4, day: 5,
    healthBoostTags: ['maintain', 'detox'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '清补柔肝，忌油腻',
    philosophy_en: 'Gentle nourishing, avoid greasy foods',
  },
  {
    name_zh: '谷雨', name_en: 'Grain Rain', pinyin: 'Gǔyǔ',
    season: 'spring', month: 4, day: 20,
    healthBoostTags: ['damp_clear'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '祛湿健脾为要，宜饮谷雨茶',
    philosophy_en: 'Prime season for damp-clearing foods',
  },

  // ── SUMMER ───────────────────────────────────────────────────────────
  {
    name_zh: '立夏', name_en: 'Start of Summer', pinyin: 'Lìxià',
    season: 'summer', month: 5, day: 6,
    healthBoostTags: ['damp_clear', 'maintain'], healthBonus: 0.20,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '健脾养心，清淡祛湿',
    philosophy_en: 'Nourish the heart, light and damp-clearing',
  },
  {
    name_zh: '小满', name_en: 'Grain Buds', pinyin: 'Xiǎomǎn',
    season: 'summer', month: 5, day: 21,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '清热利湿，忌辛辣助热',
    philosophy_en: 'Clear heat and dampness, avoid spicy',
  },
  {
    name_zh: '芒种', name_en: 'Grain in Ear', pinyin: 'Mángzhòng',
    season: 'summer', month: 6, day: 6,
    healthBoostTags: ['detox'], healthBonus: 0.18,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.15,
    philosophy_zh: '开胃健脾，清淡排毒',
    philosophy_en: 'Stimulate appetite, light detoxifying foods',
  },
  {
    name_zh: '夏至', name_en: 'Summer Solstice', pinyin: 'Xiàzhì',
    season: 'summer', month: 6, day: 21,
    healthBoostTags: ['damp_clear', 'detox'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '清热消暑，多食苦味祛火',
    philosophy_en: 'Beat summer heat, bitter foods to reduce fire',
  },
  {
    name_zh: '小暑', name_en: 'Minor Heat', pinyin: 'Xiǎoshǔ',
    season: 'summer', month: 7, day: 7,
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.25,
    flavorBoostTags: ['light'], flavorBonus: 0.12,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.20,
    philosophy_zh: '消暑利湿，绿豆薏米当道',
    philosophy_en: 'Cool and clear — mung beans and pearl barley season',
  },
  {
    name_zh: '大暑', name_en: 'Major Heat', pinyin: 'Dàshǔ',
    season: 'summer', month: 7, day: 23,
    // Strongest summer-clearing node — maximum bonuses
    healthBoostTags: ['detox', 'damp_clear'], healthBonus: 0.30,
    flavorBoostTags: ['light'], flavorBonus: 0.15,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.25,
    philosophy_zh: '一年最热，清热祛暑滋阴为要',
    philosophy_en: 'Peak heat: maximum damp-clearing and yin-nourishing',
  },

  // ── AUTUMN ───────────────────────────────────────────────────────────
  {
    name_zh: '立秋', name_en: 'Start of Autumn', pinyin: 'Lìqiū',
    season: 'autumn', month: 8, day: 7,
    // 贴秋膘 — traditional meat-gaining custom after summer
    healthBoostTags: ['muscle_gain', 'maintain'], healthBonus: 0.22,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '贴秋膘，补充夏季消耗',
    philosophy_en: 'Store autumn fat — replenish after summer',
  },
  {
    name_zh: '处暑', name_en: 'End of Heat', pinyin: 'Chǔshǔ',
    season: 'autumn', month: 8, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: ['light'], flavorBonus: 0.10,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '润肺防燥，梨银耳为佳',
    philosophy_en: 'Moisten lungs against autumn dryness',
  },
  {
    name_zh: '白露', name_en: 'White Dew', pinyin: 'Báilù',
    season: 'autumn', month: 9, day: 8,
    healthBoostTags: ['maintain'], healthBonus: 0.15,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: ['spicy'], flavorPenalty: 0.10,
    philosophy_zh: '滋阴润燥，少食辛辣',
    philosophy_en: 'Nourish yin, reduce spicy to protect lungs',
  },
  {
    name_zh: '秋分', name_en: 'Autumnal Equinox', pinyin: 'Qiūfēn',
    season: 'autumn', month: 9, day: 23,
    healthBoostTags: ['maintain'], healthBonus: 0.12,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '平补为主，阴阳调和',
    philosophy_en: 'Balanced nourishing, harmony of yin and yang',
  },
  {
    name_zh: '寒露', name_en: 'Cold Dew', pinyin: 'Hánlù',
    season: 'autumn', month: 10, day: 8,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补养胃，秋蟹正肥',
    philosophy_en: 'Warm nourishing — peak season for crab',
  },
  {
    name_zh: '霜降', name_en: "Frost's Descent", pinyin: 'Shuāngjiàng',
    season: 'autumn', month: 10, day: 23,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '羊肉栗子当道，温补正当时',
    philosophy_en: 'Lamb and chestnuts — prime warming season',
  },

  // ── WINTER ───────────────────────────────────────────────────────────
  {
    name_zh: '立冬', name_en: 'Start of Winter', pinyin: 'Lìdōng',
    season: 'winter', month: 11, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '补冬进补，饺子暖胃',
    philosophy_en: 'Begin winter nourishing — dumplings and warming broths',
  },
  {
    name_zh: '小雪', name_en: 'Minor Snow', pinyin: 'Xiǎoxuě',
    season: 'winter', month: 11, day: 22,
    healthBoostTags: ['maintain'], healthBonus: 0.20,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温补阳气，腊肉腌制正当时',
    philosophy_en: 'Warm yang energy, cured meats season begins',
  },
  {
    name_zh: '大雪', name_en: 'Major Snow', pinyin: 'Dàxuě',
    season: 'winter', month: 12, day: 7,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '大补特补，羊肉炉火锅正季',
    philosophy_en: 'Deep nourishing — mutton hotpot season',
  },
  {
    name_zh: '冬至', name_en: 'Winter Solstice', pinyin: 'Dōngzhì',
    season: 'winter', month: 12, day: 22,
    // Most important winter node — maximum tonic boost
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.35,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '一年最重要的进补节气，北饺南汤圆',
    philosophy_en: 'Greatest tonic day — dumplings north, tang yuan south',
  },
  {
    name_zh: '小寒', name_en: 'Minor Cold', pinyin: 'Xiǎohán',
    season: 'winter', month: 1, day: 6,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '温热为主，八宝粥驱寒',
    philosophy_en: 'Warming foods dominate — eight-treasure porridge',
  },
  {
    name_zh: '大寒', name_en: 'Major Cold', pinyin: 'Dàhán',
    season: 'winter', month: 1, day: 20,
    healthBoostTags: ['maintain', 'muscle_gain'], healthBonus: 0.25,
    flavorBoostTags: [], flavorBonus: 0,
    flavorPenaltyTags: [], flavorPenalty: 0,
    philosophy_zh: '岁末大补，迎接新春',
    philosophy_en: 'Year-end deep nourishing before the new year',
  },
] as (SolarTerm & { month: number; day: number })[];

// ── Solar term calculator ─────────────────────────────────────────────────

// Find the solar term currently in effect (most recently started).
// Solar terms last ~15 days; we compare using a simple days-elapsed metric.
function getCurrentSolarTerm(): SolarTerm {
  const now   = new Date();
  const month = now.getMonth() + 1; // 1-12
  const day   = now.getDate();

  // Approximate "days elapsed since this term started" — handles year wrap-around
  function daysSinceStart(term: SolarTerm & { month: number; day: number }): number {
    let monthDiff = month - term.month;
    // If the term is ahead of current month in the calendar year, treat it as ~last year's instance
    if (monthDiff < 0) monthDiff += 12;
    return monthDiff * 30 + (day - term.day); // ~30 days/month is accurate enough
  }

  let current = SOLAR_TERMS[0] as SolarTerm;
  let minElapsed = Infinity;

  for (const term of SOLAR_TERMS as (SolarTerm & { month: number; day: number })[]) {
    const elapsed = daysSinceStart(term);
    if (elapsed >= 0 && elapsed < minElapsed) {
      minElapsed = elapsed;
      current = term;
    }
  }

  return current;
}

// ── Age profile system ────────────────────────────────────────────────────

interface AgeModifiers {
  wellnessTags: string[];
  wellnessBonus: number;
  tasteBoostTags: string[];
  tasteBonus: number;
  tastePenaltyTags: string[];
  tastePenalty: number;
}

const SENIOR_MODS: AgeModifiers = {   // 70后及之前
  wellnessTags:     ['maintain', 'pregnancy', 'damp_clear'],
  wellnessBonus:    0.50,
  tasteBoostTags:   ['light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy'],
  tastePenalty:     0.30,
};
const MIDDLE_MODS: AgeModifiers = {   // 80后
  wellnessTags:     ['maintain', 'lose_weight', 'damp_clear'],
  wellnessBonus:    0.20,
  tasteBoostTags:   [],
  tasteBonus:       0,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const YOUNG_MODS: AgeModifiers = {    // 90后
  wellnessTags:     ['muscle_gain'],
  wellnessBonus:    0.25,
  tasteBoostTags:   ['spicy', 'seafood'],
  tasteBonus:       0.15,
  tastePenaltyTags: [],
  tastePenalty:     0,
};
const CHILD_MODS: AgeModifiers = {    // 00后及之后
  wellnessTags:     ['maintain'],
  wellnessBonus:    0.15,
  tasteBoostTags:   ['sweet', 'light'],
  tasteBonus:       0.20,
  tastePenaltyTags: ['spicy', 'sour'],
  tastePenalty:     0.35,
};

const AGE_GROUP_MAP: Array<{ keys: string[]; mods: AgeModifiers }> = [
  { keys: ['50后','60后','70后','pre1970','1950s','1960s','1970s','senior','elderly'], mods: SENIOR_MODS },
  { keys: ['80后','1980s','middle','adult'], mods: MIDDLE_MODS },
  { keys: ['90后','1990s','young','youth'],  mods: YOUNG_MODS  },
  { keys: ['00后','10后','2000s','2010s','child','teen','kid'],                       mods: CHILD_MODS  },
];

function resolveAgeModifiers(ageGroup: string | null): AgeModifiers {
  if (!ageGroup) return MIDDLE_MODS;
  const lower = ageGroup.toLowerCase();
  for (const { keys, mods } of AGE_GROUP_MAP) {
    if (keys.some(k => lower === k.toLowerCase() || lower.includes(k.toLowerCase()))) {
      return mods;
    }
  }
  return MIDDLE_MODS;
}

// ── Display helpers ───────────────────────────────────────────────────────

const CUISINE_LABELS: Record<string, string> = {
  sichuan:         'Sichuan Style',
  cantonese:       'Cantonese Style',
  jiangnan:        'Jiangnan Cuisine',
  northern:        'Northern Chinese',
  western:         'Western Style',
  japanese_korean: 'Japanese/Korean',
  southeast_asian: 'Southeast Asian',
};

// Extensible: add new tag → label mappings here without any DB schema change.
// The DB stores TEXT[], so any string value is valid.
const HEALTH_LABELS: Record<string, string> = {
  damp_clear:        'Damp-Clear',
  muscle_gain:       'High Protein',
  lose_weight:       'Low Calorie',
  maintain:          'Balanced',
  detox:             'Detox',
  pregnancy:         'Nourishing',
  authentic_hk:      'HK Classic',
  mood_boost:        '愉悦心情',
  anti_inflammation: '抗炎调理',
  immunity:          '增强免疫',
  beauty:            '美容养颜',
};

function deriveType(dish: any): string {
  const tags: string[] = dish.flavor_tags ?? [];
  if (tags.includes('veggie')) return 'VEGGIE';
  if (tags.includes('seafood')) return 'SEAFOOD';
  const seasonal = (dish.seasonal_tag ?? '').toLowerCase();
  if (seasonal.includes('soup') || seasonal.includes('stew')) return 'SOUP';
  return 'MEAT';
}

function deriveDescription(dish: any): string {
  const cuisine = CUISINE_LABELS[dish.origin_cuisine] ?? 'Signature Dish';
  const healthLabel = (dish.health_benefit_tags ?? [])
    .slice(0, 2)
    .map((t: string) => HEALTH_LABELS[t] ?? t.replace(/_/g, ' '))
    .join(', ');
  return healthLabel ? `${cuisine} · ${healthLabel}` : cuisine;
}

// ── Adapter: DB record → UI-friendly dish ────────────────────────────────
//
// Language is read from localStorage (set by LanguageContext) so this
// pure function stays outside React without needing the context hook.
// Fallback chain: explicit DB field → derived → empty string.

function enrichDish(dish: any, highlight: boolean): SupabaseDish {
  const lang = (localStorage.getItem('appLanguage') ?? 'zh') as 'en' | 'zh';
  const derivedDesc = deriveDescription(dish);

  const title =
    lang === 'zh'
      ? (dish.title_zh || dish.title_en || dish.title_zh || '')
      : (dish.title_en || dish.title_zh || '');

  const desc =
    lang === 'zh'
      ? (dish.description_zh || dish.description_en || derivedDesc)
      : (dish.description_en || dish.description_zh || derivedDesc);

  // Use stored URL if present, otherwise pick from curated fallback pool.
  // When AI-generated images are uploaded to storage and written to
  // dishes.image_url, this fallback is automatically bypassed.
  const img = (dish.image_url && dish.image_url.trim())
    ? dish.image_url
    : getFallbackImage(dish);

  return {
    ...dish,
    // UI adapter fields
    title,
    desc,
    img,
    // Computed classification
    is_vegetarian: (dish.flavor_tags ?? []).includes('veggie'),
    is_vegan: dish.is_vegan ?? false,
    type: deriveType(dish),
    highlight,
    // Keep for backward-compat
    description_en: dish.description_en || derivedDesc,
    // Steps — mapped from DB JSONB fields (available once gen-dish-steps runs)
    prep_steps_json: dish.prep_steps_json ?? null,
    cook_steps_json: dish.cook_steps_json ?? null,
    // 儿童友好 tag (migration 017) — drives +0.20 score boost when family has kids
    is_kid_friendly: dish.is_kid_friendly ?? false,
    // 文化背景 — null for everyday dishes, only festive/regional-iconic ones carry it
    cultural_note:   dish.cultural_note ?? null,
    // 小美 robot flags
    xiaomei_compatible:       dish.xiaomei_compatible ?? false,
    xiaomei_incompat_reason:  dish.xiaomei_incompat_reason ?? null,
    // P1 nutrition
    nutrition_kcal_per_serving: dish.nutrition_kcal_per_serving ?? undefined,
    oil_level:    dish.oil_level    ?? undefined,
    salt_level:   dish.salt_level   ?? undefined,
    sugar_level:  dish.sugar_level  ?? undefined,
    protein_source: dish.protein_source ?? undefined,
    cook_method:  dish.cook_method  ?? undefined,
    // Raw record for debugging
    _raw: dish,
  };
}

// ── Step 1: Hard filter ───────────────────────────────────────────────────

// Tag → set of main_ingredient values that should also trigger exclusion.
// Without this, a seafood-allergic user could see 鱼腐浸时蔬 because the dish
// is tagged main_ingredient='fish' but flavor_tags doesn't include 'seafood'.
// Allergen safety can't be probabilistic — we explicitly map each allergy
// keyword to all the underlying main_ingredient values that contain it.
const ALLERGEN_TO_INGREDIENTS: Record<string, Set<string>> = {
  seafood: new Set([
    'seafood','fish','shrimp','crab','shellfish','squid','scallop',
    'clam','lobster','salmon','tuna','cod','hairtail','seabass','oyster',
  ]),
  dairy:   new Set(['milk','cheese','butter','cream','yogurt']),
  peanut:  new Set(['peanut']),
  beef:    new Set(['beef']),
  egg:     new Set(['egg']),
};

function hardFilter(
  pool: any[],
  avoidTags: string[],
  avoidIngredients: string[] = [],
  vegetarianOnly = false,
): any[] {
  return pool.filter(dish => {
    // Tag-based exclusion (flavor_tags + health_benefit_tags)
    if (avoidTags.length > 0) {
      const allTags = [...(dish.flavor_tags ?? []), ...(dish.health_benefit_tags ?? [])];
      if (allTags.some(tag => avoidTags.includes(tag))) return false;
      // Allergen-safety extension: when avoidTags includes a known allergen
      // keyword (seafood/dairy/peanut/...), ALSO block any dish whose
      // main_ingredient falls under it. flavor_tags alone leaks 鱼腐浸时蔬,
      // 蜂蜜照烧三文鱼 etc. that aren't tagged 'seafood' explicitly.
      const ing = (dish.main_ingredient ?? '').toLowerCase();
      for (const allergen of avoidTags) {
        const ingSet = ALLERGEN_TO_INGREDIENTS[allergen];
        if (ingSet && ingSet.has(ing)) return false;
      }
    }
    // Ingredient-based exclusion (main_ingredient column)
    if (avoidIngredients.length > 0 && dish.main_ingredient) {
      if (avoidIngredients.includes(dish.main_ingredient)) return false;
    }
    // Vegetarian-only mode
    if (vegetarianOnly) {
      const isVeg = dish.is_vegan ||
        (dish.flavor_tags ?? []).includes('veggie') ||
        (dish.flavor_tags ?? []).includes('vegan');
      if (!isVeg) return false;
    }
    return true;
  });
}

// ── Step 2 + 3 + 6: Composite scoring ────────────────────────────────────
//
// Axis weights summary:
//   ① Hometown      30%   (5D profile)
//   ② Goal          40%   (5D profile + age modifier)
//   ③ Taste         30%   (5D profile + age modifier)
//   ④ Humidity      +0.30 bonus  (environment)
//   ⑤ Solar term    +0.12~+0.35  (culture / season)
//   ⑥ Feedback EMA  ±0.40 cap    (learned preferences — strongest recent signal)

/**
 * usagePowerUSM(n) — same power curve as useWeeklyMenu.usagePower, kept
 * inline here to avoid a circular import. Cumulative count → super-linear
 * bonus so sustained usage dominates the cold-start profile.
 */
function usagePowerUSM(n: number): number {
  if (!n) return 0;
  const sign = n >= 0 ? 1 : -1;
  return sign * Math.pow(Math.abs(n), 1.5) * 0.05;
}

function applyFeedbackScore(
  score: number,
  dish: any,
  prefScores: Record<string, number>,
): number {
  const flavorTags: string[] = dish.flavor_tags ?? [];
  const healthTags: string[] = dish.health_benefit_tags ?? [];
  const origin: string       = dish.origin_cuisine ?? '';

  // Power-curve usage layer (2026-05-17 user direction). The old linear
  // ±0.40 cap throttled long-term users — once prefScores plateaued at
  // 0.667 (the EMA saturation point) every dish saw the same +0.08
  // feedback regardless of how many 川菜 the user had kept. New: each
  // axis maps `usagePowerUSM(cnt)` to a bonus, so 5 川菜 kept ≈ +0.56,
  // 10 → +1.58, 20 → +4.47. NO outer cap — the dish-level power curve
  // already plateaus at the counter cap (25 → +6.25).
  let feedback = 0;
  for (const tag of flavorTags) {
    const col = FLAVOR_COL[tag];
    if (col && prefScores[col]) feedback += usagePowerUSM(prefScores[col]) * 0.6;
  }
  for (const tag of healthTags) {
    const col = HEALTH_COL[tag];
    if (col && prefScores[col]) feedback += usagePowerUSM(prefScores[col]) * 0.6;
  }
  const cuisineCol = CUISINE_COL[origin];
  if (cuisineCol && prefScores[cuisineCol]) feedback += usagePowerUSM(prefScores[cuisineCol]) * 1.0;

  return score + feedback;
}

// Light-bias regex: dishes whose flavor profile reads as 重口 — these get
// a per-tag −0.10 dinner penalty so a 中国营养主厨 wouldn't put them on
// the family dinner table. Lunch / breakfast are untouched.
const DINNER_HEAVY_TAGS = new Set(['salty', 'very_salty', 'oily', 'fried', 'rich']);

// 杂粮 lunch boost — Chinese dietary guideline says 午餐主食可加入杂粮
// 以补充 B 族维生素. Matches title keywords AND main_ingredient='grain'/'staple'
// so a 杂粮饭 ranks above plain white rice.
const WHOLEGRAIN_KEYWORDS = ['杂粮', '燕麦', '糙米', '玉米', '紫米', '黑米', '小米', '八宝', '藜麦', 'oat', 'quinoa', 'brown rice', 'multigrain', 'whole grain'];

function isWholegrain(d: any): boolean {
  const title = (d.title_zh ?? d.title ?? '').toLowerCase();
  return WHOLEGRAIN_KEYWORDS.some(k => title.includes(k.toLowerCase()));
}

/**
 * 菜系基础分（2026-05-17 二次澄清）。规则同 useWeeklyMenu.originBaseFor：
 * 家乡菜的权重由 hometown score axis 单独给（重的那一份在那里），base
 * 不重复叠加；没设家乡的用户走平等模式。详细见 useWeeklyMenu.ts。
 */
function originBaseForUser(dishOrigin: string, userBucket: string | null): number {
  if (!dishOrigin) return 0;
  if (dishOrigin === 'western') return -0.10;
  if (!userBucket || userBucket === 'no_preference') {
    if (['cantonese', 'northern', 'jiangnan', 'sichuan'].includes(dishOrigin)) return 0.08;
    if (['japanese_korean', 'southeast_asian'].includes(dishOrigin)) return 0.04;
    return 0;
  }
  // 家乡菜的强加分由 hometownScore axis 在 5D 打分时给，base 不重复
  if (dishOrigin === userBucket) return 0;
  if (['cantonese', 'northern', 'jiangnan', 'sichuan'].includes(dishOrigin)) return 0.04;
  if (['japanese_korean', 'southeast_asian'].includes(dishOrigin)) return 0.04;
  return 0;
}

// Premium-positioning damp: titles that feel like 快餐 / 便当 (the
// "set-meal-on-a-tray" school of Chinese cooking) get a small negative
// at lunch/dinner mains. Doesn't disqualify — just nudges down a tier so
// 厨房做出的 stir-fried + 汤+饭 layout wins over a 盖饭 box. Breakfast
// is untouched (港式茶餐厅 蛋饭 + 炒饭 is legitimate).
const FAST_FOOD_TITLE_HINTS = ['盖饭', '盖浇饭', '便当', '炒饭', '烩饭', '焗饭', '泡饭'];

// Western high-end positioning (HK premium clientele). Within origin
// 'western', lift 欧陆 (意 / 法 / 西班牙 / 地中海 / 普罗旺斯 / 摩洛哥 /
// 土耳其) and damp 美 / 英式 (三明治 / 汉堡 / 牧羊人派 / 潜艇堡 ...).
const WESTERN_FINE_DINING_HINTS = ['意式', '法式', '法棍', '牛角包', '西班牙', '地中海', '普罗旺斯', '摩洛哥', '土耳其', '巴萨米可', '蘑菇炖饭', '千层面', '披萨', '意面', '炖菜'];
const WESTERN_CASUAL_HINTS       = ['三明治', '汉堡', '玉米饼', '热狗', '玉米片', '墨西哥卷', '牧羊人派', '潜艇堡', '吐司'];

function westernHighEndBias(title: string, origin: string): number {
  if (origin !== 'western') return 0;
  if (WESTERN_FINE_DINING_HINTS.some(k => title.includes(k))) return 0.12;
  if (WESTERN_CASUAL_HINTS.some(k => title.includes(k))) return -0.08;
  return 0;
}

// Current-month → seasonal_tag bonus. DB stores 'Spring' / 'Summer' /
// 'Autumn' / 'Winter' (also lowercase variants); 'All-Season/Balanced'
// covers 80%+ of rows so we don't penalise it — just boost the in-season
// minority so a 冬瓜汤 in July or 萝卜炖排骨 in January ranks slightly
// higher. Northern hemisphere seasons (3-5 Spring, 6-8 Summer, 9-11
// Autumn, 12-2 Winter).
function currentSeasonalTag(): 'Spring' | 'Summer' | 'Autumn' | 'Winter' {
  const m = new Date().getMonth() + 1;
  if (m >= 3 && m <= 5)  return 'Spring';
  if (m >= 6 && m <= 8)  return 'Summer';
  if (m >= 9 && m <= 11) return 'Autumn';
  return 'Winter';
}

function scoreDish(
  dish: any,
  profile: UserProfile5D,
  humidity: number,
  solarTerm: SolarTerm,
  prefScores: Record<string, number>,
  spiceBoost = 0,
  hasXiaomei = false,
  mealTime: '早餐' | '午餐' | '晚餐' = '晚餐',
): number {
  const flavorTags: string[] = dish.flavor_tags ?? [];
  const healthTags: string[] = dish.health_benefit_tags ?? [];
  const origin:     string   = dish.origin_cuisine ?? '';
  const ageMods              = resolveAgeModifiers(profile.age_group);

  // ① Hometown (30%) — uses bucket helper so 八大菜系 onboarding IDs
  // (鲁/苏/浙/闽/徽/湘 ...) fall back to DB's 6-bucket origin_cuisine
  // (cantonese/sichuan/jiangnan/northern/...) until backfill细化数据。
  const hometownScore = hometownMatches(profile.hometown_cuisine, origin) ? 1.0 : 0.0;

  // ② Goal (40%) + age wellness modifier
  let goalScore = 0.0;
  if (profile.dietary_goal && healthTags.includes(profile.dietary_goal)) goalScore = 1.0;
  if (healthTags.some(t => ageMods.wellnessTags.includes(t))) {
    goalScore = Math.min(1.0, goalScore + ageMods.wellnessBonus);
  }

  // ③ Taste (30%) + age taste modifier
  let tasteScore = 0.0;
  if (profile.taste_pref && flavorTags.includes(profile.taste_pref)) tasteScore = 1.0;
  if (flavorTags.some(t => ageMods.tasteBoostTags.includes(t))) {
    tasteScore = Math.min(1.0, tasteScore + ageMods.tasteBonus);
  }
  if (flavorTags.some(t => ageMods.tastePenaltyTags.includes(t))) {
    tasteScore = Math.max(0.0, tasteScore - ageMods.tastePenalty);
  }

  let score = hometownScore * 0.30 + goalScore * 0.40 + tasteScore * 0.30;

  // 家乡权重要大（user direction 2026-05-17）。除了 5D 里的 hometownScore
  // axis (×0.30) 之外，再额外 +0.30 让家乡菜跟其他菜系拉到 0.60 的差距，
  // 跟 useWeeklyMenu.scoreForWeek 的 +0.60 hometown bonus 同口径。这意味着
  // 任何家乡设了的用户，自家菜系几乎一定排在最前面。
  if (hometownScore > 0) score += 0.30;

  // ①' Origin base score — 没设家乡的用户走平等模式（四大中餐 +0.08），
  // 设了家乡的用户家乡菜 base = 0 (避免重复加，强加分已在上面给完)。
  const _userBucket = hometownToDbBucket(profile.hometown_cuisine);
  score += originBaseForUser(origin, _userBucket);

  // ①'' Seasonality — small in-season bonus so 冬瓜 / 萝卜 / 春笋 / 秋藕
  // rise when the calendar matches. 'All-Season/Balanced' (most rows) is
  // untouched, so this can only lift the minority that have a real season.
  const seasonTag = (dish.seasonal_tag ?? '') as string;
  if (seasonTag && seasonTag.toLowerCase() === currentSeasonalTag().toLowerCase()) {
    score += 0.08;
  }

  // ①''' Premium-positioning damp — Chinese high-end chef perspective:
  // 盖饭/便当/炒饭/烩饭 read as 快餐, drag the dinner experience down a
  // notch. Breakfast is exempt (港式 + 北方 早餐里炒饭/煎饼合规)。
  const _title = (dish.title_zh ?? '').toString();
  if (mealTime !== '早餐') {
    if (FAST_FOOD_TITLE_HINTS.some(k => _title.includes(k))) {
      score -= 0.15;
    }
  }
  // ①'''' Western high-end bias — 香港高端用户视角。仅 origin='western'
  // 触发：欧陆系 +0.12 / 美式 fast-casual -0.08。
  score += westernHighEndBias(_title, origin);

  // ①'''' First-impression boost (2026-05-17 user direction)
  // 首次推荐很重要：新用户首次会话没有 prefScores 历史，全靠 profile +
  // popularity。我们对 (a) profile-match 的菜放大 1.3×，(b) 让流行度
  // (employer_crown_likes / times_kept_in_menu / health_score) 介入，
  // 让新用户第一眼看到的菜不靠随机，而是社区验证过的「都说好」的家常。
  if (isNewUserSession()) {
    // (a) profile-match 放大：goal + taste + hometown 任一匹配，乘以 0.15
    // 的额外奖励（在 hometown match 0.40 + goal 0.40 + taste 0.30 之上）
    const profileMatch = (hometownScore > 0 ? 1 : 0)
                       + (goalScore > 0    ? 1 : 0)
                       + (tasteScore > 0   ? 1 : 0);
    score += profileMatch * 0.15;

    // (b) popularity signal — small bonus on community-validated dishes.
    // health_score 范围 0–10 (DB rule)；times_kept_in_menu 通常 0–200.
    const hs:   number = Number(dish.health_score ?? 0);
    const kept: number = Number(dish.times_kept_in_menu ?? 0);
    score += (hs / 10) * 0.10;             // 满分 +0.10
    score += Math.min(kept, 50) / 50 * 0.08; // 满分 +0.08 (50+ 留存的菜)
  }

  // ④ Humidity correction (独立于节气)
  if (humidity > 85 && healthTags.includes('damp_clear')) {
    score += 0.30;
  }

  // ⑤ Solar term correction — seasonal food culture layer
  if (healthTags.some(t => solarTerm.healthBoostTags.includes(t))) {
    score += solarTerm.healthBonus;
  }
  if (flavorTags.some(t => solarTerm.flavorBoostTags.includes(t))) {
    score += solarTerm.flavorBonus;
  }
  if (flavorTags.some(t => solarTerm.flavorPenaltyTags.includes(t))) {
    score -= solarTerm.flavorPenalty;
  }

  // ⑥ User spice preference boost/penalty
  if (spiceBoost !== 0 && flavorTags.includes('spicy')) {
    score += spiceBoost;
  }

  // ⑥' 小美 robot boost — when the household has a cooking robot, float
  // robot-doable dishes to the top so the helper / parent has the option
  // of "hand it to the robot tonight". Doesn't disqualify oven-only dishes,
  // just nudges robot-doable ones up by half a flavor-tag's worth.
  if (hasXiaomei && dish.xiaomei_compatible) {
    score += 0.15;
  }

  // ⑦ Meal-specific tone (中国营养主厨 rules)
  //
  // 晚餐应该比午餐清淡 — prefer the P1 nutrition fields (oil_level /
  // salt_level / sugar_level) over the flavor_tag heuristic when they're
  // available. The new fields are LLM-evaluated per-dish so they're
  // closer to truth than 'salty' tag (which everything has).
  // Penalties tuned so a high-oil heavy main loses ≈ half a flavor-tag
  // (0.15) total, but a perfectly-aligned heavy dish can still appear.
  if (mealTime === '晚餐') {
    if (dish.oil_level   === 'high') score -= 0.08;
    if (dish.salt_level  === 'high') score -= 0.06;
    if (dish.sugar_level === 'high') score -= 0.04;
    // Falls back to the legacy flavor-tag check ONLY for dishes that
    // don't have the P1 fields yet (e.g. brand-new AI-suggested rows
    // before backfill catches up).
    if (!dish.oil_level && !dish.salt_level) {
      for (const t of flavorTags) {
        if (DINNER_HEAVY_TAGS.has(t)) score -= 0.10;
      }
    }
  }
  // 午餐主食可加入杂粮 — boost wholegrain staples (杂粮饭 / 燕麦 / 糙米 / 玉米 / 紫米 / 八宝粥 …)
  // by +0.10 at lunch only, so a staple slot prefers them over plain rice.
  if (mealTime === '午餐' && (dish.course_type === 'staple' || dish.main_ingredient === 'grain') && isWholegrain(dish)) {
    score += 0.10;
  }

  // ⑥'' 家有小孩的餐桌偏向 (migration 017 + user 2026-05-17):
  //   · is_kid_friendly: +0.20 (温和、熟悉、无辣无重油的菜显著上浮)
  //   · 早餐 + egg: +0.15 (长高需要早餐高蛋白)
  //   · 晚餐 + 钙源 (奶/豆/小鱼小虾): +0.10 (骨骼发育)
  // 三条加起来在「家有小孩 + 早餐含蛋」场景能给一道菜 +0.45，足够把
  // 「白米粥 + 咸菜」从早餐 staple slot 挤掉、换成「番茄炒蛋 + 牛奶」。
  // 读 localStorage 是 OK 的——scoreDish 在一次菜单生成里被调用 ~50 次，
  // 反正 nutri_kids 不会在一次生成中途变。
  const kidsCount = parseInt(typeof localStorage !== 'undefined' ? (localStorage.getItem('nutri_kids') ?? '0') : '0', 10);
  const hasKids = kidsCount > 0;
  if (hasKids) {
    if (dish.is_kid_friendly) score += 0.20;
    if (mealTime === '早餐') {
      const proteinSrc = (dish.protein_source ?? []) as string[];
      if (dish.main_ingredient === 'egg' || proteinSrc.includes('egg')) score += 0.15;
    }
    if (mealTime === '晚餐') {
      const proteinSrc = (dish.protein_source ?? []) as string[];
      const calciumRich =
        ['dairy', 'tofu'].includes(dish.main_ingredient ?? '') ||
        proteinSrc.some(p => ['dairy', 'tofu', 'soy'].includes(p)) ||
        flavorTags.includes('veggie') ||  // 绿叶菜也是钙源
        ((dish.title_zh ?? '').match(/(豆腐|奶|芝士|酸奶|小鱼|虾|青菜|芥兰|芥蘭|西兰花|西蘭花|油菜|苋菜|菠菜)/));
      if (calciumRich) score += 0.10;
    }
  }

  // ⑦ Learned-preference signal — folds in user_preference_scores (positive
  // for tags the user has historically accepted, negative for rejected).
  // Values from the table are roughly in [-1, 1]; we sum matches across
  // flavor_tags + health_benefit_tags + origin_cuisine + seafood detector.
  //
  // Weight is CONFIDENCE-SCALED: per the product principle "使用数据才是真
  // 数据"，as the user accumulates non-zero feedback signals across tags,
  // learned weight grows past the profile's 1.0 cap so usage gradually
  // dominates the static画像. Cold-start (0 signals) → weight 0.35 (gentle
  // nudge). After ~30 distinct non-zero tag signals → weight 1.50, which
  // exceeds the 1.0 profile baseline so a strongly-liked / strongly-disliked
  // pattern in cooking history outranks the onboarding answers.
  const learnedSignals = Object.values(prefScores)
    .filter(v => typeof v === 'number' && v !== 0).length;
  const learnedConfidence = Math.min(1, learnedSignals / 30);
  const LEARNED_WEIGHT = 0.35 + 1.15 * learnedConfidence;
  let learnedSum = 0;
  let learnedHits = 0;
  const SEAFOOD_INGS = new Set([
    'seafood','fish','shrimp','crab','shellfish','squid','scallop',
    'clam','lobster','salmon','tuna','cod','hairtail','seabass','oyster',
  ]);
  const add = (key: string) => {
    const v = prefScores[`pref_${key}`];
    if (typeof v === 'number' && v !== 0) {
      learnedSum += v;
      learnedHits += 1;
    }
  };
  flavorTags.forEach(t => add(t));
  healthTags.forEach(t => add(t));
  if (origin) add(origin);
  if (SEAFOOD_INGS.has((dish.main_ingredient ?? '').toLowerCase())) add('seafood');
  if (flavorTags.includes('veggie')) add('veggie');
  // Average across matching tags so a 10-tag dish doesn't dominate a 2-tag one
  if (learnedHits > 0) {
    score += (learnedSum / learnedHits) * LEARNED_WEIGHT;
  }

  // ⑧ Weekday speed bonus — Mon–Fri working evening prefer dishes under 20
  // min. Weekend evening (Fri-night / Sat / Sun) allows elaborate. cook_time
  // field is optional; skip the bonus when missing.
  const cookTime = (dish as any).cook_time_min;
  if (typeof cookTime === 'number' && cookTime > 0) {
    const dow = new Date().getDay();   // 0 Sun … 6 Sat
    const isWeekday = dow >= 1 && dow <= 4;  // Mon–Thu (Fri carries weekend vibe)
    if (isWeekday) {
      if (cookTime <= 15)      score += 0.15;
      else if (cookTime <= 30) score += 0.05;
      else if (cookTime > 60)  score -= 0.20;
    }
  }

  return score;
}

// ── 70/30 meat-veggie balance ─────────────────────────────────────────────

function balanceMenu(scoredPool: any[], targetSize: number): any[] {
  const veggieTarget = Math.round(targetSize * 0.30);
  const meatTarget   = targetSize - veggieTarget;

  const veggies = scoredPool.filter(d => (d.flavor_tags ?? []).includes('veggie'));
  const meats   = scoredPool.filter(d => !(d.flavor_tags ?? []).includes('veggie'));

  let selectedMeats   = meats.slice(0, meatTarget);
  let selectedVeggies = veggies.slice(0, veggieTarget);

  if (selectedVeggies.length < veggieTarget) {
    selectedMeats = [...selectedMeats, ...meats.slice(meatTarget, meatTarget + (veggieTarget - selectedVeggies.length))];
  } else if (selectedMeats.length < meatTarget) {
    selectedVeggies = [...selectedVeggies, ...veggies.slice(veggieTarget, veggieTarget + (meatTarget - selectedMeats.length))];
  }

  return [...selectedMeats, ...selectedVeggies];
}

// ── Profile fetcher (Supabase → quickPrefs → legacy fallback) ────────────

async function fetchUserProfile(): Promise<UserProfile5D & { _prefs: ReturnType<typeof getUserPrefs> }> {
  // Always read the local prefs (quickPrefs is the primary anonymous source)
  const prefs = getUserPrefs();

  const userId = getUserId();
  if (userId) {
    try {
      const { data, error } = await supabase
        .from('user_profiles')
        .select('hometown_cuisine, dietary_goal, taste_pref, age_group, avoid_tags')
        .eq('id', userId)
        .single();
      if (!error && data) {
        // Merge DB profile with local quickPrefs (local takes precedence for avoid/spice).
        // hometown_cuisine: prefer DB → local quickPrefs → null. Without the
        // local fallback, a user who set their hometown in Login but whose
        // upsert hasn't flushed yet (or whose DB row predates the column)
        // gets a 0 hometownScore and the menu ignores their cuisine choice.
        return {
          hometown_cuisine: data.hometown_cuisine ?? prefs.hometownCuisine ?? null,
          dietary_goal:     data.dietary_goal ?? prefs.dietaryGoal,
          taste_pref:       data.taste_pref ?? prefs.tastePref,
          age_group:        data.age_group ?? null,
          // Union of DB avoid_tags and locally derived avoid tags
          avoid_tags:       [...new Set([...(data.avoid_tags ?? []), ...prefs.avoidTags])],
          _prefs:           prefs,
        };
      }
    } catch { /* table not yet migrated — fall through */ }
  }

  // Anonymous path: use quickPrefs entirely. hometownCuisine comes from
  // localStorage.userHometown so the +30% hometown axis kicks in even
  // before the user has a real DB profile.
  return {
    hometown_cuisine: prefs.hometownCuisine ?? null,
    dietary_goal:     prefs.dietaryGoal,
    taste_pref:       prefs.tastePref,
    age_group:        null,
    avoid_tags:       prefs.avoidTags,
    _prefs:           prefs,
  };
}

// ── Swap options: same course_type FIRST, prefer same main_ingredient ────
//
// 原则：换菜后必须是"功能等价"的菜 — 汤换汤、主食换主食、蔬菜换蔬菜。
// 之前只过滤 main_ingredient 导致 "西班牙冷汤" (veggie/soup) 的替换池里
// 出现 "炒青菜" 这种非汤的 veggie 菜，搭配整体失衡。
//
// 现在两层：
//   1. 硬过滤：course_type 必须相同（如果有）
//   2. 软偏好：同 main_ingredient 排前面，不同的洗牌排后面

export async function fetchSwapOptions(
  currentDish: SupabaseDish,
  count = 3,
): Promise<SupabaseDish[]> {
  const ingredient = currentDish.main_ingredient;
  const courseType = currentDish.course_type;

  // Pull current user prefs so the swap drawer respects the SAME
  // allergen/spice gates the main recommend hook applies. Without this
  // step the drawer would happily offer 麻辣豆腐 to a 不吃辣 user, or
  // 芝士焗虾 to a dairy-allergic user — exactly the trust break the
  // recommendation pipeline was designed to prevent.
  const localPrefs = getUserPrefs();

  let query = supabase
    .from('dishes')
    .select(DISH_FIELDS)
    .neq('id', currentDish.id)
    .limit(count * 12); // fetch extra so hardFilter has room to survive

  // ── Hard: same course_type ──
  // soup → soup, staple → staple, main_protein → main_protein,
  // veggie_dish → veggie_dish, dessert → dessert. If course_type missing,
  // fall back to ingredient filter so the swap is still meaningful.
  if (courseType) {
    query = query.eq('course_type', courseType);
  } else if (ingredient && ingredient !== 'other') {
    query = query.eq('main_ingredient', ingredient);
  }

  const { data, error } = await query;
  if (error || !data || data.length === 0) return [];

  // ── Apply same hard filters the recommend hook uses ──
  // avoidTags        → flavor_tags / health_benefit_tags exclude (spicy, dairy, …)
  // avoidIngredients → main_ingredient exclude (peanut, beef, …)
  const filtered = hardFilter(
    data,
    localPrefs.avoidTags,
    localPrefs.avoidIngredients,
    false,  // swap drawer shouldn't force vegan even if veganOnly is set elsewhere
  );
  const pool = filtered.length > 0 ? filtered : data;  // fall back to unfiltered if pool emptied

  // ── Soft: prefer same main_ingredient ──
  // E.g. swapping 红烧肉 (pork) prefers 糖醋里脊 (pork) over 葱油鸡 (chicken),
  // but both are valid main_protein swaps.
  const sameIng  = pool.filter(d => d.main_ingredient === ingredient);
  const otherIng = pool.filter(d => d.main_ingredient !== ingredient);
  const ordered = [
    ...sameIng.sort(() => Math.random() - 0.5),
    ...otherIng.sort(() => Math.random() - 0.5),
  ];
  return ordered.slice(0, count).map(d => enrichDish(d, false));
}

// ── Hook ─────────────────────────────────────────────────────────────────

/**
 * Calculate how many dishes to recommend based on meal type + headcount + cuisine.
 *
 * Cuisine-aware rules (user-confirmed 2026-05-17):
 *
 *   中餐 (chinese / all):
 *     早餐: 3-piece dry+wet+side template (1 人 = 2)
 *     午餐: n 道菜（"4 人 4 菜 / 三菜一汤"），min 2 / max 8
 *     晚餐: n + 1 道菜（晚餐比午餐多 1）
 *
 *   西餐 (western) — Western meals are structurally simpler:
 *     早餐: 3-piece (toast + drink + egg/fruit), same as 中餐
 *     午餐: 固定 2 道（1 主食 + 1 汤）— 西餐午餐通常是一份意面/三明治 + 一份汤
 *     晚餐: n 道菜（按人数）— matches 中餐午餐 count, still simpler than 中餐晚餐
 *
 * Kids count as 0.5 effective person.
 *
 * 中餐 vs 西餐 contrast for 4 people:
 *   中餐: 早 3 / 午 4 / 晚 5         西餐: 早 3 / 午 2 / 晚 4
 *
 * Previous version was cuisine-blind and over-counted 西餐午餐 — a 4-人
 * 西餐午餐 returned 5 dishes when the family actually eats a single
 * pasta + soup combo. Cuisine-aware split matches real table-setting habit.
 */
export function calcDishCount(
  mealTime: '早餐' | '午餐' | '晚餐',
  adults: number,
  kids: number,
  cuisineMode: CuisineMode = 'chinese',
): number {
  const eff = adults + kids * 0.5;
  if (mealTime === '早餐') return eff <= 1 ? 2 : 3;

  // 西餐: lunch is fixed 2 (staple + soup); dinner scales with headcount.
  if (cuisineMode === 'western') {
    if (mealTime === '午餐') return 2;
    return Math.max(2, Math.min(8, Math.round(eff)));   // 晚餐
  }

  // 中餐 / all — full 中国家庭饭桌
  const lunch = Math.max(2, Math.min(8, Math.round(eff)));
  return mealTime === '晚餐' ? Math.min(9, lunch + 1) : lunch;
}

// ── Breakfast template: dry staple + wet drink + side ─────────────────────
//
// Without this, the top-N scoring can land 2 liquids (粥 + 豆浆) which
// doesn't match Chinese breakfast habits. We enforce structure: at least
// one solid carb (包子/馒头/油条/灌饼/煎饼/饺子/卷/吐司/三明治…) and at most
// one wet item (粥/豆浆/牛奶/米浆/糊/汤). Picks the highest-scored candidate
// from each bucket so the user still gets their preferred dishes.

const WET_BREAKFAST_KEYWORDS = ['粥', '豆浆', '豆漿', '牛奶', '羊奶', '酸奶', '米浆', '米漿', '糊', '汤', '湯', '奶昔', 'soup', 'milk', 'porridge', 'congee'];
const DRY_BREAKFAST_KEYWORDS = ['包', '馒头', '饅頭', '油条', '油條', '烧饼', '燒餅', '煎饼', '煎餅', '灌饼', '灌餅', '饺', '餃', '卷', '炒面', '炒麵', '炒饭', '炒飯', '吐司', '三明治', '汉堡', '漢堡', '司康', '可颂', '可頌', '果子', '糕', '蛋饼', '蛋餅', 'toast', 'sandwich', 'bagel', 'scone', 'burger', 'croissant', 'pancake', 'waffle', 'wrap', 'bun'];

function isWetBreakfast(d: any): boolean {
  const t = (d.title_zh ?? d.title ?? '').toLowerCase();
  return WET_BREAKFAST_KEYWORDS.some(k => t.includes(k.toLowerCase()));
}
function isDryBreakfast(d: any): boolean {
  const t = (d.title_zh ?? d.title ?? '').toLowerCase();
  return DRY_BREAKFAST_KEYWORDS.some(k => t.includes(k.toLowerCase()));
}

/**
 * Enforce the dry-staple + wet-drink + side template for breakfast.
 *
 * - 1st slot: best-scored DRY staple
 * - 2nd slot: best-scored WET drink (if target ≥ 2)
 * - 3rd slot: best-scored side that isn't already picked (if target ≥ 3),
 *             preferring egg / 蛋 / veggie_dish / non-staple
 *
 * Falls back to the original balanced list when a bucket is empty so we
 * don't accidentally show fewer dishes than requested.
 */
function applyBreakfastTemplate(sorted: any[], target: number): any[] {
  if (target <= 0 || sorted.length === 0) return [];

  // Try combo-first: culturally-paired set (豆浆+油条+蛋) rather than
  // bucket-random (粥+豆浆+海带). The combo picker reads localStorage
  // hometown to filter to the right regional set. See
  // .claude/skills/chinese-breakfast/SKILL.md for the cultural ruleset.
  try {
    const hometown = (typeof localStorage !== 'undefined' && localStorage.getItem('userHometown'))
                      ? localStorage.getItem('userHometown')!.split(',')[0] : null;
    const today = new Date();
    const dayIndex = (today.getDay() + 6) % 7;  // 0=Mon
    const combo = pickBreakfastCombo({
      pool: sorted as any,
      dayIndex,
      hometown,
      avoidIngredients: [],
      avoidTags: [],
    });
    if (combo.dishes.length === target) return combo.dishes as any[];
    // If combo couldn't fill every slot (DB gap), fall through to the
    // legacy bucket template so the user still sees `target` dishes.
  } catch { /* fall through to legacy */ }

  // ── Hometown-aware legacy fallback (2026-05-17) ──
  // When the combo picker couldn't fill every slot from BREAKFAST_COMBOS
  // (DB gap for that hometown), we used to drop straight into the global
  // sorted[0] which is heavily 北方-biased (DB has more northern breakfast
  // rows). Result: 粤 / 川 / 苏 users all surfaced 北方 breakfast despite
  // hometown set. We now prefer dishes whose origin_cuisine matches the
  // user's hometown bucket, falling through to the global pool only if
  // the regional pool is empty.
  const userHometown = (typeof localStorage !== 'undefined' && localStorage.getItem('userHometown'))
                        ? (localStorage.getItem('userHometown') ?? '').split(',')[0]
                        : null;
  const homeBucket = hometownToDbBucket(userHometown);
  const matchesBucket = (d: any) => !homeBucket || d.origin_cuisine === homeBucket;

  // Two passes per filter: regional-first, then global. If a user has no
  // hometown set (homeBucket=null) `matchesBucket` is always true and the
  // two passes collapse to the original behavior.
  const dryCandidates = sorted.filter(isDryBreakfast);
  const wetCandidates = sorted.filter(isWetBreakfast);
  const dryRegional   = dryCandidates.filter(matchesBucket);
  const wetRegional   = wetCandidates.filter(matchesBucket);

  const used = new Set<string>();
  const result: any[] = [];
  const take = (d: any | undefined) => {
    if (d && !used.has(d.id)) { used.add(d.id); result.push(d); }
  };

  // Slot 1 — dry staple (regional preferred)
  if (target >= 1) take(dryRegional[0] ?? dryCandidates[0]);
  // Slot 2 — wet drink (regional preferred)
  if (target >= 2) {
    take(wetRegional.find(d => !used.has(d.id)) ?? wetCandidates.find(d => !used.has(d.id)));
  }
  // Slot 3 — side, prefer egg first, then 凉菜 / 豆制品 / other.
  // Same regional-first treatment.
  if (target >= 3) {
    const EGG_KW = ['蛋', 'egg'];
    const SIDE_KW = ['凉拌', '腌', '腐乳', '豆干', '千张', '豆腐皮', '酱牛肉', '肉松', '肉丝'];
    const titleOf = (d: any) => ((d.title_zh ?? '') as string).toLowerCase();
    const findSide = (pool: any[]) =>
      pool.find(d => !used.has(d.id) && EGG_KW.some(k => titleOf(d).includes(k.toLowerCase())))
      ?? pool.find(d => !used.has(d.id) && SIDE_KW.some(k => titleOf(d).includes(k.toLowerCase())))
      ?? pool.find(d => !used.has(d.id) && !isWetBreakfast(d) && !isDryBreakfast(d));
    take(findSide(sorted.filter(matchesBucket)) ?? findSide(sorted));
  }
  // Pad with whatever scored highest if any slot was empty — regional first,
  // then global.
  const padPools = [sorted.filter(matchesBucket), sorted];
  for (const padPool of padPools) {
    let i = 0;
    while (result.length < target && i < padPool.length) {
      take(padPool[i]);
      i++;
    }
    if (result.length >= target) break;
  }
  return result;
}

// 绿叶蔬菜 detector — for the "晚餐 1 绿叶素菜" requirement. Detects via
// title keywords because flavor_tags 'veggie' is too broad (root veg also
// gets it). Matches 菜心 / 油麦菜 / 菠菜 / 芥兰 / 通菜 / 西兰花 / 油菜 / 生菜 / 苋菜.
const LEAFY_KEYWORDS = ['菜心', '油麦', '菠菜', '芥兰', '芥蓝', '通菜', '空心菜', '西兰花', '青菜', '生菜', '苋菜', '油菜', '小白菜', '上海青', '芦笋', '芹菜叶', 'spinach', 'kale', 'bok choy', 'cabbage'];
function isLeafyVeggie(d: any): boolean {
  const title = (d.title_zh ?? d.title ?? '').toLowerCase();
  const flavor: string[] = d.flavor_tags ?? [];
  if (!flavor.includes('veggie')) return false;
  return LEAFY_KEYWORDS.some(k => title.includes(k.toLowerCase()));
}

/**
 * 午餐模板（中国营养主厨规则）：
 *   1 主食 (course_type=staple) — 杂粮已在 scoreDish 里 +0.10 优先
 *   1 优质蛋白 (course_type=main_protein)
 *   1 蔬菜 (course_type=veggie_dish)
 *   余下槽位 → 按总分填补（汤 / 凉菜 / 配菜）
 *
 * 午餐能量占 40%，可以保留 main_protein / heavier 菜的偏好。
 */
// Pick the next item satisfying `pred`, prefer one whose cook_method
// hasn't been used yet. Falls back to any matching item if all methods
// are exhausted. Implements the "烹饪方式不重复（4 道炒太单调）" rule.
function pickWithMethodVariety(
  sorted: any[],
  pred: (d: any) => boolean,
  used: Set<string>,
  usedMethods: Set<string>,
): any | undefined {
  // First pass: same predicate AND new method
  const fresh = sorted.find(d => !used.has(d.id) && pred(d) && d.cook_method && !usedMethods.has(d.cook_method));
  if (fresh) return fresh;
  // Fallback: same predicate, allow method repeat
  return sorted.find(d => !used.has(d.id) && pred(d));
}

/**
 * 一桌饭 course_type 去重规则：staple 和 soup 在同一顿里最多各 1 道。
 * 没有这条，西餐池里 73 staple/6 main_protein 的偏斜会让 pad 阶段
 * 同桌出现 2 道 staple（披萨 + 意面）— 用户明确反对。
 */
function isPadAllowed(d: any, result: any[]): boolean {
  const ct = d.course_type ?? '';
  if (ct === 'staple' && result.some(r => r.course_type === 'staple')) return false;
  if (ct === 'soup'   && result.some(r => r.course_type === 'soup'))   return false;
  return true;
}

function applyLunchTemplate(sorted: any[], target: number, cuisineMode: CuisineMode = 'chinese'): any[] {
  if (target <= 0 || sorted.length === 0) return [];
  const used = new Set<string>();
  const usedMethods = new Set<string>();
  const result: any[] = [];
  const take = (d: any | undefined) => {
    if (d && !used.has(d.id)) {
      used.add(d.id);
      if (d.cook_method) usedMethods.add(d.cook_method);
      result.push(d);
    }
  };

  // 西餐午餐 = 1 主食 + 1 汤（user-confirmed 2026-05-17）。西餐午餐通常是单
  // 一碗意面 / 三明治 + 一份汤，pasta+pizza 同桌不是西式饭桌习惯。
  if (cuisineMode === 'western') {
    if (target >= 1) take(pickWithMethodVariety(sorted, d => d.course_type === 'staple', used, usedMethods));
    if (target >= 2) {
      const soup = pickWithMethodVariety(sorted, d => d.course_type === 'soup', used, usedMethods);
      if (soup) take(soup);
      else take(pickWithMethodVariety(sorted, d => d.course_type === 'veggie_dish', used, usedMethods));
    }
    // 西餐午餐固定 2 道，不 pad
    return result;
  }

  // 中餐午餐 — staple + main_protein + veggie_dish + 按分数补，但不超出
  // 1 staple / 1 soup（isPadAllowed 守护）。
  if (target >= 1) take(pickWithMethodVariety(sorted, d => d.course_type === 'staple',       used, usedMethods));
  if (target >= 2) take(pickWithMethodVariety(sorted, d => d.course_type === 'main_protein', used, usedMethods));
  if (target >= 3) take(pickWithMethodVariety(sorted, d => d.course_type === 'veggie_dish',  used, usedMethods));
  while (result.length < target) {
    const next = sorted.find(d => !used.has(d.id) && isPadAllowed(d, result) && d.cook_method && !usedMethods.has(d.cook_method))
                ?? sorted.find(d => !used.has(d.id) && isPadAllowed(d, result));
    if (!next) break;
    take(next);
  }
  return result;
}

/**
 * 晚餐模板（中国营养主厨规则）：
 *   1 主食 (course_type=staple) — 晚餐主食可以是米饭，杂粮 boost 不强制
 *   1 主菜 (course_type=main_protein) — 一道荤
 *   1 绿叶蔬菜 (isLeafyVeggie)        — 绿叶蒜蓉清炒为主
 *   必带 1 汤 (course_type=soup)       — 冬瓜汤 / 萝卜汤 / 紫菜汤 …
 *   余下槽位 → 按总分填补
 *
 * 汤强制：如果池子里 soup 一道都没有，就只能 fallback，但记 console 警示，
 * 让上层知道该补 soup 数据。
 */
function applyDinnerTemplate(sorted: any[], target: number, _cuisineMode: CuisineMode = 'chinese'): any[] {
  if (target <= 0 || sorted.length === 0) return [];
  const used = new Set<string>();
  const usedMethods = new Set<string>();
  const result: any[] = [];
  const take = (d: any | undefined) => {
    if (d && !used.has(d.id)) {
      used.add(d.id);
      if (d.cook_method) usedMethods.add(d.cook_method);
      result.push(d);
    }
  };

  if (target >= 1) take(pickWithMethodVariety(sorted, d => d.course_type === 'staple',       used, usedMethods));
  if (target >= 2) take(pickWithMethodVariety(sorted, d => d.course_type === 'main_protein', used, usedMethods));
  if (target >= 3) {
    const leafy = pickWithMethodVariety(sorted, isLeafyVeggie, used, usedMethods);
    if (leafy) take(leafy);
    else take(pickWithMethodVariety(sorted, d => d.course_type === 'veggie_dish', used, usedMethods));
  }
  if (target >= 4) {
    const soup = pickWithMethodVariety(sorted, d => d.course_type === 'soup', used, usedMethods);
    if (soup) take(soup);
    else if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.warn('[dinnerTemplate] no soup in pool — dinner without 汤 violates the 营养主厨 rule');
    }
  }
  // Pad — 守护 staple / soup 最多各 1（isPadAllowed），否则西餐池 73 staple
  // 会把 pad slot 全填成 pizza+pasta+sandwich。
  while (result.length < target) {
    const next = sorted.find(d => !used.has(d.id) && isPadAllowed(d, result) && d.cook_method && !usedMethods.has(d.cook_method))
                ?? sorted.find(d => !used.has(d.id) && isPadAllowed(d, result));
    if (!next) break;
    take(next);
  }
  return result;
}

export function useRecommendDishes(
  mealTime: '早餐' | '午餐' | '晚餐' = '晚餐',
  veganOnly = false,
  adults = 2,
  kids = 0,
  cuisineMode: CuisineMode = 'chinese',
) {
  const [recommendedDishes, setRecommendedDishes] = useState<SupabaseDish[]>([]);
  const [currentSolarTerm, setCurrentSolarTerm]   = useState<SolarTerm | null>(null);
  const [prefScores, setPrefScores]               = useState<Record<string, number>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);

  const refresh = useCallback(() => setRefreshKey(k => k + 1), []);

  // Re-run when user updates preferences (from Settings or QuickSetup)
  useEffect(() => {
    const handler = () => setRefreshKey(k => k + 1);
    window.addEventListener('nutri-prefs-changed', handler);
    return () => window.removeEventListener('nutri-prefs-changed', handler);
  }, []);

  // Map UI label → DB meal_type values to include.
  // 午餐 intentionally includes 'dinner' — Chinese home lunch and dinner
  // share the same dish repertoire; most dinner dishes are equally suitable
  // for lunch. Without this, lunch returns 0 results (no lunch-tagged dishes).
  const mealTypeFilter: Record<string, string[]> = {
    '早餐': ['breakfast'],
    '午餐': ['lunch', 'dinner', 'all'],
    '晚餐': ['dinner', 'all'],
  };
  const allowedMealTypes = mealTypeFilter[mealTime] ?? ['dinner', 'all'];
  const dishCount = calcDishCount(mealTime, adults, kids, cuisineMode);

  useEffect(() => {
    let cancelled = false;

    async function run() {
      try {
        setLoading(true);

        const humidity  = parseFloat(localStorage.getItem('current_humidity') ?? '75');
        const solarTerm = getCurrentSolarTerm();
        const profile   = await fetchUserProfile();

        // Load feedback-learned preference scores (best effort)
        let scores: Record<string, number> = {};
        const userId = getUserId();
        if (userId) {
          const { data: scoreRow } = await supabase
            .from('user_preference_scores')
            .select('*')
            .eq('user_id', userId)
            .single();
          if (scoreRow) scores = scoreRow as Record<string, number>;
        }

        // Filter by meal_type. `meal_type` may be NULL on older rows (treat as dinner/all).
        // We use 'in' + include NULL via OR filter.
        let dishQuery = supabase
          .from('dishes')
          .select(DISH_FIELDS)
          .or(`meal_type.in.(${allowedMealTypes.join(',')}),meal_type.is.null`)
          .limit(400);

        // 净食模式: only return is_vegan dishes
        if (veganOnly) {
          dishQuery = dishQuery.eq('is_vegan', true);
        }

        // Cuisine pre-filter — push the 中餐/西餐 toggle down to the DB so
        // top-N scoring picks from the right bucket instead of the UI
        // stripping survivors after the fact.
        dishQuery = applyCuisineFilter(dishQuery, cuisineMode);

        const { data: allDishes, error: fetchErr } = await dishQuery;
        if (fetchErr) throw fetchErr;

        const localPrefs = profile._prefs;
        const filtered = hardFilter(
          allDishes ?? [],
          profile.avoid_tags,
          localPrefs.avoidIngredients,
          localPrefs.vegetarianOnly,
        );

        // "我有小美料理机" toggle — read at scoring time so toggling the
        // switch in Settings affects the next menu refresh without a
        // hook remount.
        const hasXiaomei = localStorage.getItem('has_xiaomei_robot') === 'true';

        const sorted = filtered
          .map(dish => ({
            dish,
            score: scoreDish(dish, profile, humidity, solarTerm, scores, localPrefs.spiceBoost, hasXiaomei, mealTime),
          }))
          .sort((a, b) => b.score - a.score)
          .map(s => s.dish);

        // Each meal type now has its own structural template — straight
        // 70/30 meat/veggie balanceMenu was 营养主厨-blind (没汤、没绿叶、
        // 没主食保证). Templates enforce: 早餐 dry+wet+side, 午餐
        // staple+protein+veggie, 晚餐 staple+protein+leafy+soup.
        const balanced = mealTime === '早餐' ? applyBreakfastTemplate(sorted, dishCount)
                       : mealTime === '午餐' ? applyLunchTemplate(sorted, dishCount, cuisineMode)
                       :                       applyDinnerTemplate(sorted, dishCount, cuisineMode);

        // ── 餐后水果 slot ─────────────────────────────────────────────
        // 午餐 / 晚餐 各挂一份时令水果。不受 cuisine filter (水果中西通用)，
        // 不计入 dishCount (calcDishCount 不变)。早餐不加 (早餐已有 dry+wet+
        // side 自有结构)。按节气优先 + 当日轮换。
        if (mealTime !== '早餐') {
          try {
            const { data: fruitRows } = await supabase
              .from('dishes')
              .select(DISH_FIELDS)
              .eq('course_type', 'fruit')
              .limit(30);
            const fruits = (fruitRows ?? []).filter(f => {
              // Honor avoid tags / vegetarian — fruits are inherently vegan
              // but allergen tags (e.g. 芒果 latex cross-reactivity) still apply.
              const tags = [...(f.flavor_tags ?? []), ...(f.health_benefit_tags ?? [])];
              if (profile.avoid_tags.some(t => tags.includes(t))) return false;
              return true;
            });
            if (fruits.length > 0) {
              const seasonal = fruits.filter(f => f.seasonal_tag === solarTerm.season || f.seasonal_tag === 'all-season');
              const pool = seasonal.length > 0 ? seasonal : fruits;
              const dailyIndex = new Date().getDate() + (mealTime === '晚餐' ? 7 : 0);
              const fruit = pool[dailyIndex % pool.length];
              if (fruit) balanced.push(fruit);
            }
          } catch { /* fruit slot is optional — skip on error */ }
        }

        if (cancelled) return;

        setCurrentSolarTerm(solarTerm);
        setPrefScores(scores);
        setRecommendedDishes(balanced.map((d, i) => enrichDish(d, i === 0)));
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Failed to fetch dishes');
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    run();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshKey, mealTime, veganOnly, adults, kids, cuisineMode]);

  return { recommendedDishes, currentSolarTerm, prefScores, loading, error, refresh };
}
