/**
 * MenuProposal — A / B / C proposal card with one-tap adoption.
 *
 * Renders three week-plan candidates side-by-side as compact summary cards
 * (cuisine mix preview + week-start date). The active candidate index can
 * be flipped without committing, then one tap on "采纳 X" calls onAdopt to
 * lock it in. Adoption persists the choice via useChatSession.chooseProposal
 * and (commit ③) triggers downstream user_weekly_menus upsert.
 *
 * The detailed diff narrative ("A 偏 X / B 偏 Y / C 偏 Z") is generated by
 * the AI bubble next to this card, not by this component — keeping the
 * component static and prop-driven.
 */
import { useState } from 'react';
import type { WeekPlan, ProposalChoice } from '../hooks/useChatSession';

interface Props {
  proposals: WeekPlan[];
  chosen?:   ProposalChoice;
  onAdopt:   (choice: ProposalChoice) => void;
}

const TABS: ProposalChoice[] = ['A', 'B', 'C'];

// Compact one-line cuisine preview pulled from the proposal's first day:
// helps the user eyeball the difference between A/B/C without expanding.
function summarizeProposal(plan: WeekPlan): string {
  const firstDay = plan.days?.[0];
  if (!firstDay) return '—';
  const titles = (firstDay.dishes ?? []).slice(0, 3).map(d => d.title_zh || d.title_en || '').filter(Boolean);
  if (titles.length === 0) return '空菜单';
  return titles.join(' · ');
}

export default function MenuProposal({ proposals, chosen, onAdopt }: Props) {
  const [activeIdx, setActiveIdx] = useState<number>(
    chosen ? TABS.indexOf(chosen) : 0
  );

  if (!proposals || proposals.length === 0) return null;

  const active = proposals[Math.min(activeIdx, proposals.length - 1)];
  const activeChoice: ProposalChoice = TABS[activeIdx] ?? 'A';
  const isAdopted = chosen === activeChoice;

  return (
    <div className="rounded-2xl bg-white border border-black/[0.06] overflow-hidden shadow-sm">
      {/* Tabs */}
      <div className="flex" style={{ background: 'rgba(0,0,0,0.03)' }}>
        {TABS.slice(0, proposals.length).map((label, idx) => {
          const isActive = idx === activeIdx;
          const isThisChosen = chosen === label;
          return (
            <button key={label} onClick={() => setActiveIdx(idx)}
              className="flex-1 py-2.5 font-bold transition-all active:scale-95"
              style={{
                fontSize: 13,
                background: isActive ? 'white' : 'transparent',
                color:      isActive ? '#FF5A1F' : 'rgba(0,0,0,0.45)',
                borderBottom: isActive ? '2px solid #FF5A1F' : '2px solid transparent',
              }}>
              方案 {label}
              {isThisChosen && (
                <span className="ml-1" style={{ fontSize: 11 }}>✓</span>
              )}
            </button>
          );
        })}
      </div>

      {/* Body */}
      <div className="px-4 py-3 flex flex-col gap-2">
        <p style={{ fontSize: 11, color: 'rgba(0,0,0,0.42)', fontWeight: 600, letterSpacing: '0.04em' }}>
          {active.weekStart} · 周一首餐预览
        </p>
        <p style={{ fontSize: 13, color: '#1a1a1a', lineHeight: 1.5 }}>
          {summarizeProposal(active)}
        </p>
        <p style={{ fontSize: 11, color: 'rgba(0,0,0,0.42)' }}>
          {active.days?.length ?? 0} 天 · 共 {(active.days ?? []).reduce((sum, d) => sum + (d.dishes?.length ?? 0), 0)} 道
        </p>
      </div>

      {/* Adopt CTA */}
      <button onClick={() => onAdopt(activeChoice)} disabled={isAdopted}
        className="w-full py-3 font-bold text-white transition-all active:scale-[0.99] disabled:opacity-60"
        style={{
          background: isAdopted ? '#25D366' : '#FF5A1F',
          fontSize: 14,
        }}>
        {isAdopted ? `✓ 已采纳方案 ${activeChoice}` : `采纳方案 ${activeChoice}，存到这周菜单`}
      </button>
    </div>
  );
}
