/**
 * MenuProposal — A / B / C proposal card with one-tap adoption.
 *
 * Renders three week-plan candidates side-by-side as compact summary cards
 * (cuisine mix preview + week-start date). The active candidate index can
 * be flipped without committing, then one tap on "采纳 X" calls onAdopt to
 * lock it in. Adoption persists the choice via useChatSession.chooseProposal
 * and (commit ③) triggers downstream user_weekly_menus upsert.
 *
 * The detailed diff narrative ("A 偏 X / B 偏 Y / C 偏 Z") is generated by
 * the AI bubble next to this card, not by this component — keeping the
 * component static and prop-driven.
 */
import { useState } from 'react';
import type { WeekPlan, ProposalChoice } from '../hooks/useChatSession';
import { VARIANT_META, type ProposalVariant } from '../lib/proposalEngine';

interface Props {
  proposals: WeekPlan[];
  chosen?:   ProposalChoice;
  onAdopt:   (choice: ProposalChoice) => void;
  /** Parent-controlled disable (e.g. while another adopt is in flight).
   *  ORs with the internal isAdopted-derived disable; default false. */
  disabled?: boolean;
  /** TICKET-034 §A — semantic labels per proposal (A/B/C) so the user
   *  reads "均衡推荐 / 应季应景 / 投你所好" instead of "方案 1 / 2 / 3
   *  with no apparent difference". Optional + parallel to proposals[];
   *  omit for backward compatibility with skeleton callers. */
  variants?: readonly ProposalVariant[];
}

const TABS: ProposalChoice[] = ['A', 'B', 'C'];

// Compact one-line cuisine preview pulled from the proposal's first day:
// helps the user eyeball the difference between A/B/C without expanding.
function summarizeProposal(plan: WeekPlan): string {
  const firstDay = plan.days?.[0];
  if (!firstDay) return '—';
  const titles = (firstDay.dishes ?? []).slice(0, 3).map(d => d.title_zh || d.title_en || '').filter(Boolean);
  if (titles.length === 0) return '空菜单';
  return titles.join(' · ');
}

export default function MenuProposal({ proposals, chosen, onAdopt, disabled = false, variants }: Props) {
  const [activeIdx, setActiveIdx] = useState<number>(
    chosen ? TABS.indexOf(chosen) : 0
  );

  if (!proposals || proposals.length === 0) return null;

  const active = proposals[Math.min(activeIdx, proposals.length - 1)];
  const activeChoice: ProposalChoice = TABS[activeIdx] ?? 'A';
  const isAdopted = chosen === activeChoice;

  return (
    <div className="rounded-2xl bg-white border border-black/[0.06] overflow-hidden shadow-sm">
      {/* Tabs — each shows label + (optional) variant chip on a 2-row stack */}
      <div className="flex" style={{ background: 'rgba(0,0,0,0.03)' }}>
        {TABS.slice(0, proposals.length).map((label, idx) => {
          const isActive = idx === activeIdx;
          const isThisChosen = chosen === label;
          const variantMeta = variants && variants[idx] ? VARIANT_META[variants[idx]] : null;
          return (
            <button key={label} onClick={() => setActiveIdx(idx)}
              className="flex-1 py-2 px-1 font-bold transition-all active:scale-95 flex flex-col items-center gap-0.5"
              style={{
                background: isActive ? 'white' : 'transparent',
                color:      isActive ? '#FF5A1F' : 'rgba(0,0,0,0.45)',
                borderBottom: isActive ? '2px solid #FF5A1F' : '2px solid transparent',
              }}>
              <span style={{ fontSize: 13, lineHeight: 1.1 }}>
                方案 {label}
                {isThisChosen && <span className="ml-1" style={{ fontSize: 11 }}>✓</span>}
              </span>
              {variantMeta && (
                <span style={{
                  fontSize: 10,
                  fontWeight: 600,
                  color: isActive ? '#FF5A1F' : 'rgba(0,0,0,0.40)',
                  letterSpacing: '0.02em',
                }}>
                  {variantMeta.label}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* Body */}
      <div className="px-4 py-3 flex flex-col gap-2">
        {/* Active variant subtitle (TICKET-034 §A) — adds one line of context
            so the user knows WHY this proposal differs from the others. */}
        {variants && variants[activeIdx] && (
          <p style={{ fontSize: 10.5, color: 'rgba(255,90,31,0.85)', fontWeight: 600, lineHeight: 1.5 }}>
            {VARIANT_META[variants[activeIdx]].description}
          </p>
        )}
        <p style={{ fontSize: 11, color: 'rgba(0,0,0,0.42)', fontWeight: 600, letterSpacing: '0.04em' }}>
          {active.weekStart} · 周一首餐预览
        </p>
        <p style={{ fontSize: 13, color: '#1a1a1a', lineHeight: 1.5 }}>
          {summarizeProposal(active)}
        </p>
        <p style={{ fontSize: 11, color: 'rgba(0,0,0,0.42)' }}>
          {active.days?.length ?? 0} 天 · 共 {(active.days ?? []).reduce((sum, d) => sum + (d.dishes?.length ?? 0), 0)} 道
        </p>
      </div>

      {/* Adopt CTA. `disabled` ORs the parent-controlled inflight flag with
          the internal isAdopted state so a second tap during a 3-second
          countdown is a no-op (anti double-click). */}
      <button onClick={() => onAdopt(activeChoice)} disabled={isAdopted || disabled}
        className="w-full py-3 font-bold text-white transition-all active:scale-[0.99] disabled:opacity-60 flex items-center justify-center gap-1.5"
        style={{
          background: isAdopted ? '#25D366' : '#FF5A1F',
          fontSize: 14,
        }}>
        {isAdopted
          ? `✓ 已采用方案 ${activeChoice}，跳转中…`
          : disabled
            ? '处理中…'
            : <>采用方案 {activeChoice} → 存到这周菜单</>}
      </button>
    </div>
  );
}
