/**
 * seed-meat-54.ts — 54 道肉菜从第二本食谱书拆出，全部 meal_type='all'
 * 让午餐 + 晚餐池都能选到，不会出现在早餐池。
 *
 * 来源：用户提供的肉类食谱目录截图 4 张（簡易家常菜 / 節日宴客菜 /
 * 派對小食 / 簡易碟頭飯麵 / 養生肉食）。中文用简体。
 *
 * 流程要求 (MEMORY.md · dish_seed_pipeline)：seed 之后必须立刻跑
 *   gen-dish-steps-claude → backfill-dish-nutrition → backfill-xiaomei-compat
 */
import pg from 'pg';
import { config } from 'dotenv';
config();

interface DishSeed {
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  origin_cuisine: string;
  main_ingredient: string;
  course_type: 'main_protein' | 'staple' | 'soup';
  flavor_tags: string[];
  health_benefit_tags: string[];
  is_vegan: boolean;
  execution_level: number;
}

const SEEDS: DishSeed[] = [
  // ── 簡易家常菜 (18) ──
  { title_zh:'秘制香茅猪扒', title_en:'Secret Lemongrass Pork Chop',
    description_zh:'猪扒用香茅、姜葱蒜腌透，煎至两面金黄，香茅清香解腻。',
    description_en:'Pork chops marinated in lemongrass, pan-seared golden.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'番茄牛肉炒蛋', title_en:'Tomato Beef Scrambled Egg',
    description_zh:'牛肉片与番茄炒出汁水，倒入蛋液炒成嫩滑，三色配饭。',
    description_en:'Beef and tomato stir-fry folded into scrambled egg.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['sweet','sour','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'豉汁蒸排骨', title_en:'Steamed Pork Ribs with Black Bean Sauce',
    description_zh:'排骨腌豉汁蒜末，铺在白饭上蒸 20 分钟，茶楼经典。',
    description_en:'Pork ribs steamed with fermented black bean sauce.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','umami'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'蒜片炒一口牛', title_en:'Garlic Beef Bites',
    description_zh:'牛肉切骰子大小，配蒜片黑椒爆炒，下酒下饭都好。',
    description_en:'Bite-sized beef stir-fried with crispy garlic chips.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'土鱿蒸肉饼', title_en:'Steamed Pork Patty with Dried Squid',
    description_zh:'猪肉剁烂混入泡软的土鱿粒，加盐糖酱油蒸 15 分钟。',
    description_en:'Steamed pork patty with rehydrated dried squid.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','umami'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'沙嗲粉丝肥牛煲', title_en:'Satay Beef & Vermicelli Pot',
    description_zh:'肥牛卷与粉丝煮沙嗲酱底，砂锅上桌咕嘟咕嘟。',
    description_en:'Beef rolls and vermicelli in satay sauce hotpot.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'蜜汁叉烧', title_en:'Honey Char Siu',
    description_zh:'梅头猪肉腌叉烧酱蜂蜜，烤至焦糖化，淋蜜汁切片。',
    description_en:'Pork shoulder marinated in BBQ sauce + honey, roasted to caramel glaze.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'叉烧炒滑蛋', title_en:'Char Siu Scrambled Egg',
    description_zh:'叉烧切粒与嫩蛋同炒，金黄滑嫩，茶餐厅家常。',
    description_en:'Char siu diced with silky scrambled eggs.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'萝卜焖牛肋条', title_en:'Daikon Braised Beef Brisket',
    description_zh:'牛肋条与白萝卜慢炖 2 小时，汤汁浓稠下饭。',
    description_en:'Beef brisket and daikon slow-braised 2 hours.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'咸肉杂锦炒藕片', title_en:'Cured Pork Lotus Root Stir-fry',
    description_zh:'咸猪肉片配藕片、彩椒、木耳快炒，咸鲜爽脆。',
    description_en:'Cured pork with lotus root, peppers, fungus stir-fry.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','salty'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'沙嗲牛肉炒杂菌', title_en:'Satay Beef with Mixed Mushrooms',
    description_zh:'牛肉片与多种菌菇炒沙嗲酱，蛋白质纤维双重补充。',
    description_en:'Beef and mixed mushrooms stir-fried with satay sauce.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'家乡豆腐', title_en:'Hometown Tofu',
    description_zh:'豆腐与肉末、香菇、青菜慢煮，浓郁汤汁裹豆腐。',
    description_en:'Tofu with minced pork, mushroom, greens — homely.',
    origin_cuisine:'cantonese', main_ingredient:'tofu', course_type:'main_protein',
    flavor_tags:['savory','umami'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'胜瓜云耳炒猪颈肉', title_en:'Loofah & Wood Ear with Pork Neck',
    description_zh:'丝瓜（胜瓜）、云耳与猪颈肉快炒，清爽不油腻。',
    description_en:'Loofah and wood ear with pork neck stir-fry.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','detox'], is_vegan:false, execution_level:1 },
  { title_zh:'菜心炒牛肉', title_en:'Choy Sum with Beef',
    description_zh:'菜心焯水保翠绿，与腌牛肉片快炒蒜蓉调味。',
    description_en:'Blanched choy sum stir-fried with marinated beef.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'韭菜肉碎煎蛋角', title_en:'Chive Pork Egg Pocket',
    description_zh:'韭菜碎与肉末拌蛋液，平底锅煎成三角蛋饼。',
    description_en:'Chive and minced pork folded into triangular egg pocket.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'虾酱蒸猪肉', title_en:'Shrimp Paste Steamed Pork',
    description_zh:'梅头肉切片腌虾酱蒸 15 分钟，咸鲜浓郁。',
    description_en:'Pork shoulder slices steamed with shrimp paste.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','umami','salty'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'韭菜花炒咸肉', title_en:'Chive Flower with Cured Pork',
    description_zh:'韭菜花脆嫩，与咸肉片快炒，咸鲜下饭。',
    description_en:'Tender chive flowers stir-fried with cured pork slices.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'惹味猪软骨', title_en:'Spicy Pork Cartilage',
    description_zh:'猪软骨炸至外脆内嫩，淋椒盐辣酱，下酒佳品。',
    description_en:'Crispy pork cartilage with spicy salt-pepper seasoning.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['spicy','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },

  // ── 節日宴客菜 (17) ──
  { title_zh:'松化脆皮烧肉', title_en:'Crispy Skin Roast Pork',
    description_zh:'五花肉表皮戳孔抹盐烤至冒泡，皮脆肉嫩。',
    description_en:'Roast pork belly with bubbled crispy skin.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','rich'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'回锅肉', title_en:'Twice-cooked Pork',
    description_zh:'五花肉先煮后切片回炒，配青椒蒜苗豆瓣酱，川菜经典。',
    description_en:'Sichuan twice-cooked pork with bell peppers and bean paste.',
    origin_cuisine:'sichuan', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'不油腻红烧肉', title_en:'Light Braised Pork Belly',
    description_zh:'五花肉先焯水去油，再红烧调味，浓味不腻。',
    description_en:'Blanched pork belly braised in soy sauce — less greasy.',
    origin_cuisine:'jiangnan', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'菠萝咕噜肉', title_en:'Sweet Sour Pork with Pineapple',
    description_zh:'里脊裹粉炸金黄，配菠萝彩椒糖醋酱，老少咸宜。',
    description_en:'Crispy pork in sweet-sour sauce with pineapple.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','sour'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'南乳花生焖猪手', title_en:'Red Bean Curd Pig Trotter with Peanuts',
    description_zh:'猪手与南乳花生慢炖 2 小时，胶原蛋白丰富。',
    description_en:'Pig trotter braised with red bean curd and peanuts 2h.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','sweet'], health_benefit_tags:['nourish','high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'酱爆西施肉', title_en:'Stir-fried "Beauty" Pork',
    description_zh:'里脊肉切薄片爆炒，淋甜面酱，色泽诱人。',
    description_en:'Pork tenderloin slices wok-tossed with sweet bean sauce.',
    origin_cuisine:'jiangnan', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'黑豚猪肉杂菜卷', title_en:'Kurobuta Pork Veggie Roll',
    description_zh:'黑豚猪肉薄片卷彩椒、芦笋、金针菇，煎至两面金黄。',
    description_en:'Kurobuta pork rolled with veggies, pan-seared.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'猪肉酿节瓜甫', title_en:'Stuffed Wax Gourd with Pork',
    description_zh:'节瓜挖空填入猪肉馅，蒸熟后淋汤汁，清爽营养。',
    description_en:'Wax gourd stuffed with pork, steamed with broth.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'黑椒牛仔骨', title_en:'Black Pepper Beef Ribs',
    description_zh:'牛仔骨腌黑胡椒酱，煎或烤至五分熟，多汁鲜嫩。',
    description_en:'Black pepper beef short ribs grilled medium-rare.',
    origin_cuisine:'western', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'百合甜豆炒猪柳', title_en:'Lily Bulb Sugar Snap Pork',
    description_zh:'猪柳切丝与百合、甜豆同炒，清甜爽脆。',
    description_en:'Pork tenderloin with lily bulb and sugar snap peas.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['light','sweet'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'南瓜咖喱焖排骨', title_en:'Pumpkin Curry Pork Ribs',
    description_zh:'排骨与南瓜炖咖喱酱，南瓜化作浓稠酱汁。',
    description_en:'Pork ribs and pumpkin braised in curry sauce.',
    origin_cuisine:'southeast_asian', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['aromatic','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'牛柳炒双花', title_en:'Beef with Broccoli & Cauliflower',
    description_zh:'牛柳片与西兰花、菜花快炒，蒜香蚝油调味。',
    description_en:'Beef strips with broccoli and cauliflower stir-fry.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'葱爆羊肉', title_en:'Scallion Lamb',
    description_zh:'羊肉片爆炒大葱段，孜然香气浓郁。',
    description_en:'Lamb slices stir-fried with scallion and cumin.',
    origin_cuisine:'northern', main_ingredient:'lamb', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'中式牛柳', title_en:'Chinese-style Beef Strips',
    description_zh:'牛柳腌蚝油，与洋葱青椒炒，浓郁中式风味。',
    description_en:'Beef strips with onion and pepper in oyster sauce.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'松子仁炒牛柳粒', title_en:'Pine Nut Beef Cubes',
    description_zh:'牛柳切粒爆炒，配香脆松子仁，宴客高级感。',
    description_en:'Diced beef stir-fried with crispy pine nuts.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'香煎莲藕饼', title_en:'Pan-fried Lotus Root Patty',
    description_zh:'莲藕剁碎拌肉末调味，捏成圆饼煎至金黄。',
    description_en:'Lotus root patty mixed with minced pork, pan-fried golden.',
    origin_cuisine:'jiangnan', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'XO酱翠玉瓜炒玻璃肉', title_en:'XO Sauce Zucchini & Pork',
    description_zh:'翠玉瓜（西葫芦）与玻璃肉片配 XO 酱爆炒，色香味俱全。',
    description_en:'Zucchini and pork in XO sauce stir-fry.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','umami'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },

  // ── 派對小食 (11) ──
  { title_zh:'自制熏蹄', title_en:'Smoked Pig Trotter',
    description_zh:'猪蹄卤制后用茶叶熏香，切片冷食或热吃皆宜。',
    description_en:'Braised then tea-smoked pig trotter, sliced.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:2 },
  { title_zh:'黑椒牛柳串烧', title_en:'Black Pepper Beef Skewers',
    description_zh:'牛柳切方块腌黑椒，串签烤或煎，宴会人气小食。',
    description_en:'Black pepper beef cubes skewered and grilled.',
    origin_cuisine:'western', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'梅子猪肘骨', title_en:'Plum Sauce Pork Knuckle',
    description_zh:'猪肘骨与梅子同炖，酸甜开胃，年节常做。',
    description_en:'Pork knuckle braised with sour plum sauce.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','sour'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'五香牛腱', title_en:'Five-spice Beef Shank',
    description_zh:'牛腱用八角桂皮卤煮 2 小时，切薄片冷盘。',
    description_en:'Beef shank braised with five-spice 2h, sliced cold.',
    origin_cuisine:'northern', main_ingredient:'beef', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'沙嗲猪肉串', title_en:'Satay Pork Skewers',
    description_zh:'猪肉切条腌沙嗲酱，串签烤或煎，配花生酱。',
    description_en:'Pork strips skewered, satay marinade, served with peanut sauce.',
    origin_cuisine:'southeast_asian', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'泰式香茅猪颈肉', title_en:'Thai Lemongrass Pork Neck',
    description_zh:'猪颈肉腌香茅鱼露泰式调料，烤或煎至金黄。',
    description_en:'Pork neck marinated in Thai lemongrass fish sauce, grilled.',
    origin_cuisine:'southeast_asian', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'肉丝春卷', title_en:'Pork Shred Spring Rolls',
    description_zh:'春卷皮裹肉丝韭黄豆芽，下锅炸至金黄酥脆。',
    description_en:'Spring rolls stuffed with pork shred, chives, bean sprout.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'香煎羊扒', title_en:'Pan-seared Lamb Chop',
    description_zh:'羊扒腌迷迭香蒜蓉，煎至五分熟，外脆内嫩。',
    description_en:'Lamb chop marinated in rosemary garlic, seared medium-rare.',
    origin_cuisine:'western', main_ingredient:'lamb', course_type:'main_protein',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'芝麻蜜汁猪扒', title_en:'Sesame Honey Pork Chop',
    description_zh:'猪扒腌蜂蜜酱油，煎熟后撒白芝麻，甜咸交织。',
    description_en:'Honey-glazed pork chop topped with sesame.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'main_protein',
    flavor_tags:['sweet','savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'肉酱意粉', title_en:'Bolognese Spaghetti',
    description_zh:'意大利肉酱浇意粉，番茄香浓郁，西式经典。',
    description_en:'Spaghetti bolognese with rich tomato meat sauce.',
    origin_cuisine:'western', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },

  // ── 簡易碟頭飯麵 (6) — these are staples ──
  { title_zh:'港式焗猪扒饭', title_en:'HK Baked Pork Chop Rice',
    description_zh:'猪扒、番茄酱、芝士铺在炒饭上焗至芝士融化，港式茶餐厅经典。',
    description_en:'Pork chop, tomato sauce, cheese baked over fried rice — HK classic.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','rich','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'孜然羊肉煎蛋饭', title_en:'Cumin Lamb Fried Egg Rice',
    description_zh:'羊肉孜然爆炒，配煎蛋盖饭，北方风味。',
    description_en:'Cumin-spiced lamb with fried egg over rice.',
    origin_cuisine:'northern', main_ingredient:'lamb', course_type:'staple',
    flavor_tags:['aromatic','spicy'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'日式滑蛋猪扒饭', title_en:'Japanese Pork Chop & Egg Rice',
    description_zh:'日式炸猪扒切片，与洋葱蛋液同煮，盖白饭。',
    description_en:'Japanese tonkatsu pork chop with egg over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'日式牛肉饭', title_en:'Japanese Beef Bowl (Gyudon)',
    description_zh:'牛肉片与洋葱用日式甜咸酱汁煮，浇白饭即吉野家牛丼。',
    description_en:'Sliced beef with onion in Japanese sweet-soy over rice (gyudon).',
    origin_cuisine:'japanese_korean', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'肉丝炒面', title_en:'Shredded Pork Lo Mein',
    description_zh:'肉丝、青菜、面条一同翻炒，咸鲜下饭。',
    description_en:'Stir-fried noodles with pork shreds and greens.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'葱油叉烧丝炒公仔面', title_en:'Char Siu Scallion Oil Instant Noodles',
    description_zh:'公仔面焯水，配叉烧丝、葱油酱拌炒，港式快食。',
    description_en:'Instant noodles tossed with char siu shreds and scallion oil.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },

  // ── 養生肉食 (4) — these are soups ──
  { title_zh:'鲜茅根生地薏仁炖鲍鱼骨', title_en:'Reed Root & Abalone Bone Soup',
    description_zh:'鲜茅根、生地、薏仁与鲍鱼骨炖 3 小时，清热祛湿。',
    description_en:'Fresh reed root, rehmannia, Job\'s tears with abalone bone — heat-clearing.',
    origin_cuisine:'cantonese', main_ingredient:'shellfish', course_type:'soup',
    flavor_tags:['light','aromatic'], health_benefit_tags:['damp_clear','nourish'], is_vegan:false, execution_level:2 },
  { title_zh:'药膳补身羊肉煲', title_en:'Medicinal Lamb Stew Pot',
    description_zh:'羊肉与当归、黄芪、枸杞慢炖 2 小时，冬季补身。',
    description_en:'Lamb with angelica, astragalus, goji slow-stewed 2h.',
    origin_cuisine:'northern', main_ingredient:'lamb', course_type:'soup',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['nourish','high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'正气新会陈皮骨', title_en:'New Society Chenpi Pork Rib Soup',
    description_zh:'排骨与新会陈皮、姜片炖煮，理气健脾。',
    description_en:'Pork ribs with aged tangerine peel and ginger — qi-soothing.',
    origin_cuisine:'cantonese', main_ingredient:'pork', course_type:'soup',
    flavor_tags:['light','aromatic'], health_benefit_tags:['maintain','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'梨香牛肋肉煲', title_en:'Pear Beef Brisket Pot',
    description_zh:'雪梨与牛肋肉炖煮，梨子润肺，牛肉补气。',
    description_en:'Snow pear stewed with beef brisket — lung-moistening + qi-boosting.',
    origin_cuisine:'cantonese', main_ingredient:'beef', course_type:'soup',
    flavor_tags:['sweet','light'], health_benefit_tags:['nourish','high_protein'], is_vegan:false, execution_level:1 },
];

(async () => {
  const db = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  let inserted = 0, skipped = 0;
  for (const s of SEEDS) {
    const exists = await db.query(`SELECT 1 FROM dishes WHERE title_zh = $1 LIMIT 1`, [s.title_zh]);
    if (exists.rows.length > 0) {
      console.log(`  ⏭  ${s.title_zh} (已存在)`);
      skipped++;
      continue;
    }
    await db.query(`
      INSERT INTO dishes(
        title_zh, title_en, description_zh, description_en,
        meal_type, origin_cuisine, main_ingredient, course_type,
        flavor_tags, health_benefit_tags,
        seasonal_tag, is_vegan, execution_level
      ) VALUES ($1,$2,$3,$4,'all',$5,$6,$7,$8,$9,'All-Season/Balanced',$10,$11)
    `, [
      s.title_zh, s.title_en, s.description_zh, s.description_en,
      s.origin_cuisine, s.main_ingredient, s.course_type,
      s.flavor_tags, s.health_benefit_tags,
      s.is_vegan, s.execution_level,
    ]);
    console.log(`  ✅ ${s.title_zh.padEnd(16)} [${s.origin_cuisine.padEnd(15)} / ${s.main_ingredient.padEnd(10)} / ${s.course_type}]`);
    inserted++;
  }
  console.log(`\n📊 Done: ${inserted} inserted · ${skipped} skipped (meal_type='all' — 午 + 晚 都可见)`);
  await db.end();
})();
