/**
 * seed-rice-bowls-60.ts — 60 道盖饭从食谱书拆出来，全部 meal_type='lunch'。
 *
 * 来源：用户提供 4 张食谱目录截图 (補給能量 / 日式 / 餐廳級 / 超簡單)。
 * 中文用简体；菜系按口味归类，不全是中餐 — 日式/西式/韩式都打对应
 * origin_cuisine，让选"中餐 only"的用户不会被打扰。
 *
 * 流程要求 (见 MEMORY.md · dish_seed_pipeline)：seed 之后必须立刻跑
 *   gen-dish-steps-claude → backfill-dish-nutrition → backfill-xiaomei-compat
 * 才算完工。这个脚本本身只 seed metadata。
 */
import pg from 'pg';
import { config } from 'dotenv';
config();

interface DishSeed {
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  origin_cuisine: string;
  main_ingredient: string;
  course_type: 'staple';
  flavor_tags: string[];
  health_benefit_tags: string[];
  is_vegan: boolean;
  execution_level: number;
}

const SEEDS: DishSeed[] = [
  // ── 補給能量好吃蓋飯 (20) ──
  { title_zh:'红萝卜鸡蛋起司盖饭', title_en:'Carrot Egg Cheese Rice Bowl',
    description_zh:'红萝卜丝炒香配蛋液和起司丝，盖在白饭上烤至起司融化。',
    description_en:'Carrot, scrambled egg, melted cheese over rice.',
    origin_cuisine:'western', main_ingredient:'egg', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'大酱锅盖饭', title_en:'Soybean Paste Stew Rice Bowl',
    description_zh:'韩式大酱锅汤汁配豆腐和蔬菜，浇白饭上，浓郁咸香。',
    description_en:'Korean doenjang jjigae with tofu and veg over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'soy', course_type:'staple',
    flavor_tags:['savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'根茎蔬菜鱼板盖饭', title_en:'Root Veg & Fish Cake Rice Bowl',
    description_zh:'白萝卜、胡萝卜、莲藕配日式鱼板煮制，盖白饭。',
    description_en:'Daikon, carrot, lotus root with fish cake over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['maintain','detox'], is_vegan:false, execution_level:1 },
  { title_zh:'芝麻菇海带盖饭', title_en:'Sesame Mushroom Seaweed Rice Bowl',
    description_zh:'蘑菇和海带丝快炒，撒白芝麻盖白饭，植物性高纤。',
    description_en:'Stir-fried mushroom and kelp with sesame over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'veggie', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['detox','low_sodium'], is_vegan:true, execution_level:1 },
  { title_zh:'豆腐虾干菠菜盖饭', title_en:'Tofu Dried Shrimp Spinach Rice Bowl',
    description_zh:'豆腐炒虾干和菠菜，调味清淡，钙铁兼备。',
    description_en:'Tofu, dried shrimp, spinach stir-fry over rice.',
    origin_cuisine:'cantonese', main_ingredient:'shellfish', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'麻婆豆腐盖饭', title_en:'Mapo Tofu Rice Bowl',
    description_zh:'经典麻婆豆腐浇白饭上，麻辣下饭。',
    description_en:'Classic mapo tofu over rice — numbingly spicy.',
    origin_cuisine:'sichuan', main_ingredient:'tofu', course_type:'staple',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'鹰嘴豆番茄咖喱盖饭', title_en:'Chickpea Tomato Curry Rice Bowl',
    description_zh:'鹰嘴豆与番茄炖咖喱，配香米饭，植物蛋白丰富。',
    description_en:'Chickpea-tomato curry over basmati rice.',
    origin_cuisine:'western', main_ingredient:'soy', course_type:'staple',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:true, execution_level:1 },
  { title_zh:'四川风白菜炸酱盖饭', title_en:'Sichuan Napa Zha Jiang Rice Bowl',
    description_zh:'肉末炸酱配白菜丝，麻辣口味浇饭。',
    description_en:'Sichuan-style zha jiang with napa cabbage over rice.',
    origin_cuisine:'sichuan', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'明太鱼黄豆芽盖饭', title_en:'Pollock Bean Sprout Rice Bowl',
    description_zh:'韩式明太鱼与黄豆芽煮汤汁，浇白饭。',
    description_en:'Korean pollock with bean sprouts over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['savory','light'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'烫鱼片盖饭', title_en:'Poached Fish Slice Rice Bowl',
    description_zh:'鱼片用热汤烫熟，配青菜浇饭，清淡鲜美。',
    description_en:'Poached fish slices over rice with greens.',
    origin_cuisine:'cantonese', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'辣鱿鱼黄豆芽盖饭', title_en:'Spicy Squid Bean Sprout Rice Bowl',
    description_zh:'鱿鱼快炒辣椒酱配黄豆芽，韩式辣味盖饭。',
    description_en:'Spicy stir-fried squid with bean sprouts over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'shellfish', course_type:'staple',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'美乃滋炸鸡盖饭', title_en:'Mayo Fried Chicken Rice Bowl',
    description_zh:'炸鸡块淋美乃滋酱配白饭，咸香微甜。',
    description_en:'Fried chicken with Japanese mayo over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'辣炒鸡排盖饭', title_en:'Spicy Chicken Chop Rice Bowl',
    description_zh:'韩式辣酱炒鸡块配年糕和高丽菜，浇白饭。',
    description_en:'Korean dakgalbi spicy chicken over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'韭菜杂菜盖饭', title_en:'Chive Japchae Rice Bowl',
    description_zh:'韩式杂菜（粉丝+韭菜+蔬菜+牛肉）盖白饭。',
    description_en:'Korean japchae glass noodles over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'猪绞肉盖饭', title_en:'Minced Pork Rice Bowl',
    description_zh:'猪肉末炒香配葱姜蒜，浇白饭，家常下饭菜。',
    description_en:'Minced pork stir-fry over rice — quick and savory.',
    origin_cuisine:'northern', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'五花肉水芹盖饭', title_en:'Pork Belly Water Celery Rice Bowl',
    description_zh:'五花肉切片炒水芹菜，韩式调味，配白饭。',
    description_en:'Pork belly with water celery over rice, Korean style.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'柚子烤肉香菇盖饭', title_en:'Yuzu BBQ Pork Mushroom Rice Bowl',
    description_zh:'柚子酱烤五花肉配香菇，淋酱汁盖白饭。',
    description_en:'Yuzu-glazed pork belly with shiitake over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['sweet','savory','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'牛肉蒜片盖饭', title_en:'Beef Garlic Chip Rice Bowl',
    description_zh:'牛肉片炒蒜片，黑胡椒调味，盖白饭。',
    description_en:'Beef slices with crispy garlic chips over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'熏鸭泡菜盖饭', title_en:'Smoked Duck Kimchi Rice Bowl',
    description_zh:'熏鸭片配韩式泡菜炒香，浇白饭。',
    description_en:'Smoked duck with kimchi stir-fry over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['spicy','sour','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'牛油果午餐肉盖饭', title_en:'Avocado Spam Rice Bowl',
    description_zh:'午餐肉煎香配牛油果切片，浇白饭，夏威夷风。',
    description_en:'Pan-fried SPAM with avocado over rice — Hawaiian style.',
    origin_cuisine:'western', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','rich'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },

  // ── 日式蓋飯/丼 (14) ──
  { title_zh:'茄子丼', title_en:'Eggplant Donburi',
    description_zh:'茄子煎软配酱油味淋酱，盖白饭，清淡素食选择。',
    description_en:'Soft-fried eggplant with soy glaze over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'veggie', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['detox','maintain'], is_vegan:true, execution_level:1 },
  { title_zh:'三文鱼丼', title_en:'Salmon Donburi',
    description_zh:'三文鱼煎或腌渍生切，配寿司饭，富含 omega-3。',
    description_en:'Salmon (cooked or sashimi-cured) over sushi rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['light','umami'], health_benefit_tags:['high_protein','nourish','omega3'], is_vegan:false, execution_level:1 },
  { title_zh:'鲭鱼丼', title_en:'Mackerel Donburi',
    description_zh:'鲭鱼味噌煮或盐烤，盖在白饭上，深海鱼营养价值高。',
    description_en:'Miso-simmered or salt-grilled mackerel over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['savory'], health_benefit_tags:['high_protein','omega3'], is_vegan:false, execution_level:1 },
  { title_zh:'鳗鱼丼', title_en:'Unagi Donburi',
    description_zh:'蒲烧鳗鱼淋甜酱汁，盖白饭，日式经典夏季补品。',
    description_en:'Glazed eel over rice — Japanese summer classic.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'亲子丼', title_en:'Oyakodon',
    description_zh:'鸡肉与鸡蛋同煮，"亲子"取自鸡和蛋的关系，温润下饭。',
    description_en:'Chicken and egg simmered in dashi over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'炸猪排丼', title_en:'Katsudon',
    description_zh:'日式炸猪排切块，与洋葱、鸡蛋同煮，盖白饭。',
    description_en:'Tonkatsu pork cutlet simmered with egg and onion over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'姜烧猪肉丼', title_en:'Ginger Pork Donburi',
    description_zh:'猪肉片用姜汁酱油炒香，盖白饭，开胃下饭。',
    description_en:'Ginger soy pork over rice — Japanese home classic.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'叉烧丼', title_en:'Chashu Donburi',
    description_zh:'日式叉烧切片，温泉蛋，盖在白饭上淋酱汁。',
    description_en:'Japanese chashu pork with onsen egg over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'绞肉丼', title_en:'Soboro Donburi',
    description_zh:'三色绞肉饭：肉松、蛋松、青菜碎三色铺白饭。',
    description_en:'Tri-color minced meat, egg, and greens over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'土豆炖肉丼', title_en:'Nikujaga Donburi',
    description_zh:'日式肉土豆甜咸炖煮，浇白饭，温暖家常味。',
    description_en:'Japanese beef-potato stew over rice — homely warming.',
    origin_cuisine:'japanese_korean', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['sweet','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'纳豆番茄丼', title_en:'Natto Tomato Donburi',
    description_zh:'纳豆配新鲜番茄丁，淋酱油盖白饭，植物性高蛋白。',
    description_en:'Natto and tomato over rice — plant-based protein boost.',
    origin_cuisine:'japanese_korean', main_ingredient:'soy', course_type:'staple',
    flavor_tags:['umami','sour'], health_benefit_tags:['high_protein','detox'], is_vegan:true, execution_level:1 },
  { title_zh:'海鲜综合丼', title_en:'Mixed Seafood Donburi',
    description_zh:'生鱼片、虾、扇贝、鱼籽混合，盖寿司饭。',
    description_en:'Sashimi mix (salmon, tuna, shrimp, scallop, roe) over sushi rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['light','umami'], health_benefit_tags:['high_protein','omega3','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'御好烧丼', title_en:'Okonomiyaki Donburi',
    description_zh:'日式御好烧切块盖饭，淋酱汁与美乃滋，关西风。',
    description_en:'Okonomiyaki pieces with sauce over rice — Kansai-style.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'日式牛肉烩饭', title_en:'Hayashi Rice',
    description_zh:'牛肉片与洋葱用日式番茄褐酱煮制，盖白饭。',
    description_en:'Beef and onion in tomato demi-glace over rice (hayashi).',
    origin_cuisine:'japanese_korean', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','sweet'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },

  // ── 餐廳級的特色蓋飯 (12) ──
  { title_zh:'牛油果明太鱼子盖饭', title_en:'Avocado Tarako Rice Bowl',
    description_zh:'牛油果片配明太鱼子，撒海苔丝，淋酱油，餐厅级简餐。',
    description_en:'Avocado with tarako (pollock roe) and nori over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['umami','rich'], health_benefit_tags:['omega3','high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'彩虹盖饭', title_en:'Rainbow Donburi',
    description_zh:'多色生鱼片（三文鱼/金枪鱼/比目鱼/鱼籽）铺寿司饭，色彩缤纷。',
    description_en:'Mixed sashimi rainbow (salmon/tuna/whitefish/roe) over sushi rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['light','umami'], health_benefit_tags:['high_protein','omega3'], is_vegan:false, execution_level:2 },
  { title_zh:'法式炖菜盖饭', title_en:'Ratatouille Rice Bowl',
    description_zh:'法式蔬菜炖（茄子/番茄/西葫芦/彩椒）盖白饭，地中海风。',
    description_en:'French ratatouille (eggplant/tomato/zucchini/pepper) over rice.',
    origin_cuisine:'western', main_ingredient:'veggie', course_type:'staple',
    flavor_tags:['light','aromatic'], health_benefit_tags:['detox','maintain'], is_vegan:true, execution_level:1 },
  { title_zh:'小虾盒子盖饭', title_en:'Shrimp Box Rice Bowl',
    description_zh:'虾仁拌时蔬装小盒子摆盘，配白饭。',
    description_en:'Shrimp and veggie in a presentation box with rice.',
    origin_cuisine:'cantonese', main_ingredient:'shrimp', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'炒码盖饭', title_en:'Champon Rice Bowl',
    description_zh:'韩式炒码海鲜辣汤汁配蔬菜，盖白饭，麻辣开胃。',
    description_en:'Korean jjamppong-style spicy seafood stir-fry over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'shellfish', course_type:'staple',
    flavor_tags:['spicy','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:2 },
  { title_zh:'滑溜三丝盖饭', title_en:'Silky Three-Shred Rice Bowl',
    description_zh:'肉丝、笋丝、香菇丝勾芡浇白饭，软嫩入口。',
    description_en:'Pork, bamboo, shiitake shreds in gravy over rice.',
    origin_cuisine:'northern', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','umami'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'芝麻参鸡盖饭', title_en:'Sesame Samgye Chicken Rice Bowl',
    description_zh:'参鸡汤的鸡肉撕丝配人参鸡汤汁，撒芝麻盖白饭。',
    description_en:'Samgyetang chicken shreds with ginseng broth over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['savory','aromatic'], health_benefit_tags:['high_protein','nourish'], is_vegan:false, execution_level:2 },
  { title_zh:'巴萨米可炸鸡盖饭', title_en:'Balsamic Fried Chicken Rice Bowl',
    description_zh:'炸鸡淋意大利巴萨米可醋酱，盖白饭，西式酸甜。',
    description_en:'Fried chicken with balsamic glaze over rice.',
    origin_cuisine:'western', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['sour','sweet','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'泰式猪肉盖饭', title_en:'Thai Pork Rice Bowl',
    description_zh:'打抛猪肉（罗勒叶+辣椒+鱼露炒）盖白饭，配煎蛋。',
    description_en:'Thai pad krapow pork with fried egg over rice.',
    origin_cuisine:'southeast_asian', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['spicy','aromatic'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'夏威夷米汉堡盖饭', title_en:'Loco Moco',
    description_zh:'夏威夷洛可莫可：汉堡牛肉饼 + 煎蛋 + 棕酱浇白饭。',
    description_en:'Hawaiian loco moco: beef patty + fried egg + brown gravy over rice.',
    origin_cuisine:'western', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','rich'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:1 },
  { title_zh:'章鱼饭', title_en:'Octopus Rice',
    description_zh:'章鱼丁与米同煮，吸饱海鲜味，日式炊饭。',
    description_en:'Octopus and rice cooked together — Japanese takikomi style.',
    origin_cuisine:'japanese_korean', main_ingredient:'shellfish', course_type:'staple',
    flavor_tags:['light','umami'], health_benefit_tags:['high_protein','low_sodium'], is_vegan:false, execution_level:1 },
  { title_zh:'牛排盖饭', title_en:'Steak Rice Bowl',
    description_zh:'煎牛排切片配焦糖洋葱，淋红酒酱汁盖白饭。',
    description_en:'Pan-seared steak slices with caramelized onion over rice.',
    origin_cuisine:'western', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory','rich'], health_benefit_tags:['high_protein','muscle_gain'], is_vegan:false, execution_level:2 },

  // ── 輕鬆準備超簡單蓋飯 (14) ──
  { title_zh:'西葫芦蛋盖饭', title_en:'Zucchini Egg Rice Bowl',
    description_zh:'西葫芦切丝与鸡蛋同炒，盖白饭，清爽家常。',
    description_en:'Zucchini and egg stir-fry over rice — quick home meal.',
    origin_cuisine:'northern', main_ingredient:'egg', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'番茄蛋盖饭', title_en:'Tomato Egg Rice Bowl',
    description_zh:'番茄炒蛋的浓汁浇白饭上，国民下饭菜。',
    description_en:'Classic tomato scrambled egg over rice — national favorite.',
    origin_cuisine:'northern', main_ingredient:'egg', course_type:'staple',
    flavor_tags:['sweet','sour','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'半熟蛋盖饭', title_en:'Soft-Boiled Egg Rice Bowl',
    description_zh:'半熟温泉蛋打在热白饭上，淋酱油拌匀。',
    description_en:'Onsen tamago over hot rice with soy sauce drizzle.',
    origin_cuisine:'japanese_korean', main_ingredient:'egg', course_type:'staple',
    flavor_tags:['light','savory','rich'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'花椰菜咖喱虾盖饭', title_en:'Cauliflower Curry Shrimp Rice Bowl',
    description_zh:'花椰菜与虾仁配椰浆咖喱，盖白饭，泰式风。',
    description_en:'Cauliflower & shrimp coconut curry over rice.',
    origin_cuisine:'southeast_asian', main_ingredient:'shrimp', course_type:'staple',
    flavor_tags:['aromatic','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'凤尾鱼豆腐盖饭', title_en:'Anchovy Tofu Rice Bowl',
    description_zh:'豆腐配炒凤尾鱼丝，咸鲜下饭。',
    description_en:'Tofu with stir-fried anchovy over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['savory','salty'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'绿豆芽炒鸡盖饭', title_en:'Bean Sprout Chicken Rice Bowl',
    description_zh:'鸡丁与绿豆芽快炒，盖白饭，清淡高蛋白。',
    description_en:'Chicken and bean sprout stir-fry over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'poultry', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','lose_weight'], is_vegan:false, execution_level:1 },
  { title_zh:'包菜猪肉盖饭', title_en:'Cabbage Pork Rice Bowl',
    description_zh:'包菜与猪肉片快炒，调清淡咸鲜，盖白饭。',
    description_en:'Cabbage and pork stir-fry over rice — quick and light.',
    origin_cuisine:'northern', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['light','savory'], health_benefit_tags:['high_protein','maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'菠菜牛肉盖饭', title_en:'Spinach Beef Rice Bowl',
    description_zh:'菠菜与牛肉片快炒，蒜蓉调味，盖白饭，补铁。',
    description_en:'Spinach and beef stir-fry with garlic over rice — iron boost.',
    origin_cuisine:'northern', main_ingredient:'beef', course_type:'staple',
    flavor_tags:['savory'], health_benefit_tags:['high_protein','muscle_gain','nourish'], is_vegan:false, execution_level:1 },
  { title_zh:'洋葱鱼板盖饭', title_en:'Onion Fish Cake Rice Bowl',
    description_zh:'洋葱与鱼板煮日式甜咸酱汁，盖白饭。',
    description_en:'Onion and fish cake in Japanese sweet-soy sauce over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['sweet','savory'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'平菇蟹肉盖饭', title_en:'Oyster Mushroom Crab Rice Bowl',
    description_zh:'平菇与蟹肉炒香勾芡，盖白饭，鲜味十足。',
    description_en:'Oyster mushroom and crab in thick sauce over rice.',
    origin_cuisine:'japanese_korean', main_ingredient:'shellfish', course_type:'staple',
    flavor_tags:['umami','savory'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'美乃滋金枪鱼盖饭', title_en:'Mayo Tuna Rice Bowl',
    description_zh:'罐头金枪鱼拌美乃滋盖白饭，撒葱花，5 分钟搞定。',
    description_en:'Canned tuna with mayo over rice — 5-minute meal.',
    origin_cuisine:'japanese_korean', main_ingredient:'fish', course_type:'staple',
    flavor_tags:['savory','rich'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
  { title_zh:'蔬菜香肠盖饭', title_en:'Veg & Sausage Rice Bowl',
    description_zh:'香肠切片与蔬菜快炒，盖白饭，简单饱腹。',
    description_en:'Sausage and veg stir-fry over rice — simple filling.',
    origin_cuisine:'western', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','rich'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'培根洋葱盖饭', title_en:'Bacon Onion Rice Bowl',
    description_zh:'培根煎香配焦糖洋葱，盖白饭撒葱花，洋食家常。',
    description_en:'Crispy bacon with caramelized onion over rice.',
    origin_cuisine:'western', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sweet','rich'], health_benefit_tags:['maintain'], is_vegan:false, execution_level:1 },
  { title_zh:'饺子盖饭', title_en:'Gyoza Rice Bowl',
    description_zh:'煎饺切块铺白饭上，淋黑醋酱油，下饭新法。',
    description_en:'Pan-fried gyoza chunks over rice with black vinegar soy.',
    origin_cuisine:'japanese_korean', main_ingredient:'pork', course_type:'staple',
    flavor_tags:['savory','sour'], health_benefit_tags:['high_protein'], is_vegan:false, execution_level:1 },
];

(async () => {
  const db = new pg.Pool({ connectionString: process.env.DATABASE_URL });
  let inserted = 0, skipped = 0;
  for (const s of SEEDS) {
    const exists = await db.query(`SELECT 1 FROM dishes WHERE title_zh = $1 LIMIT 1`, [s.title_zh]);
    if (exists.rows.length > 0) {
      console.log(`  ⏭  ${s.title_zh} (已存在)`);
      skipped++;
      continue;
    }
    await db.query(`
      INSERT INTO dishes(
        title_zh, title_en, description_zh, description_en,
        meal_type, origin_cuisine, main_ingredient, course_type,
        flavor_tags, health_benefit_tags,
        seasonal_tag, is_vegan, execution_level
      ) VALUES ($1,$2,$3,$4,'lunch',$5,$6,$7,$8,$9,'All-Season/Balanced',$10,$11)
    `, [
      s.title_zh, s.title_en, s.description_zh, s.description_en,
      s.origin_cuisine, s.main_ingredient, s.course_type,
      s.flavor_tags, s.health_benefit_tags,
      s.is_vegan, s.execution_level,
    ]);
    console.log(`  ✅ ${s.title_zh.padEnd(18)} [${s.origin_cuisine.padEnd(15)} / ${s.main_ingredient}]`);
    inserted++;
  }
  console.log(`\n📊 Done: ${inserted} inserted · ${skipped} skipped`);
  await db.end();
})();
